# Generated by Django 5.2.9 on 2025-12-07 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Ficha Numerológica', 'verbose_name_plural': 'Fichas Numerológicas'},
        ),
        migrations.AddField(
            model_name='ficha',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ficha',
            name='patient_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_fichas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(limit_choices_to={'profile__user_type': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
                'unique_together': {('therapist', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('initial', 'Sesión Inicial'), ('followup', 'Seguimiento'), ('consultation', 'Consulta'), ('closure', 'Cierre')], default='followup', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True, help_text='Notas privadas solo para el terapeuta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.patient')),
                ('related_fichas', models.ManyToManyField(blank=True, related_name='sessions', to='api.ficha')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Terapéutica',
                'verbose_name_plural': 'Sesiones Terapéuticas',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='TherapistNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Separar con comas', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_notes', to='api.ficha')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_notes', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota del Terapeuta',
                'verbose_name_plural': 'Notas de Terapeutas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('personal', 'Usuario Personal'), ('therapist', 'Terapeuta Profesional')], default='personal', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('subscription_status', models.CharField(choices=[('trial', 'Período de Prueba'), ('active', 'Activa'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('max_fichas_per_month', models.IntegerField(default=10)),
                ('fichas_created_this_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
