# Generated by Django 5.2.9 on 2025-12-07 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ficha_options_ficha_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_full_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fecha Bloqueada',
                'verbose_name_plural': 'Fechas Bloqueadas',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('service_type', models.CharField(choices=[('session', 'Sesión en Vivo'), ('reading', 'Lectura/Análisis'), ('course', 'Curso Grabado'), ('workshop', 'Taller en Vivo'), ('retreat', 'Retiro Virtual'), ('membership', 'Membresía Mensual'), ('package', 'Paquete de Sesiones'), ('meditation', 'Meditación Grabada')], max_length=20)),
                ('short_description', models.CharField(max_length=500)),
                ('full_description', models.TextField()),
                ('benefits', models.JSONField(default=list, help_text='Lista de beneficios del servicio')),
                ('includes', models.JSONField(default=list, help_text='Qué incluye el servicio')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_label', models.CharField(blank=True, help_text="Ej: 'Primera sesión'", max_length=100)),
                ('duration_value', models.IntegerField(help_text='Valor numérico de duración')),
                ('duration_type', models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días'), ('months', 'Meses'), ('years', 'Años'), ('lifetime', 'Acceso de por vida')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_booking', models.BooleanField(default=True, help_text='Requiere reserva de horario')),
                ('max_participants', models.IntegerField(blank=True, help_text='Para talleres/retiros', null=True)),
                ('platform', models.CharField(default='Zoom', help_text='Zoom, Google Meet, Discord, etc.', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sesiones', 'Sesiones Individuales'), ('lecturas', 'Lecturas y Análisis'), ('formacion', 'Formación Profesional'), ('talleres', 'Talleres y Retiros'), ('contenido', 'Contenido Digital'), ('acompanamiento', 'Acompañamiento Continuo'), ('comunidad', 'Comunidad y Membresía')], max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono (lucide-react)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Cantidad de este servicio incluido')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Europe/Madrid', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_services', models.ManyToManyField(blank=True, related_name='available_slots', to='api.service')),
            ],
            options={
                'verbose_name': 'Horario Disponible',
                'verbose_name_plural': 'Horarios Disponibles',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(help_text='% de descuento respecto a precio individual')),
                ('validity_months', models.IntegerField(default=12, help_text='Meses de validez desde la compra')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(through='api.PackageService', to='api.service')),
            ],
            options={
                'verbose_name': 'Paquete de Servicios',
                'verbose_name_plural': 'Paquetes de Servicios',
                'ordering': ['-discount_percentage', 'name'],
            },
        ),
        migrations.AddField(
            model_name='packageservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicepackage'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Madrid', max_length=50)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('client_notes', models.TextField(blank=True, help_text='Notas del cliente')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('stripe', 'Tarjeta (Stripe)'), ('paypal', 'PayPal'), ('bizum', 'Bizum'), ('transfer', 'Transferencia Bancaria')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('canceled', 'Cancelada'), ('rescheduled', 'Reprogramada')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255)),
                ('bizum_transaction_id', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Google Meet link')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('canceled', 'Cancelada'), ('rescheduled', 'Reprogramada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.service')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.servicepackage')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='packageservice',
            unique_together={('package', 'service')},
        ),
    ]
