# Generated by Django 5.2.9 on 2025-12-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blockeddate_service_servicecategory_packageservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_patients_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_patients',
            field=models.IntegerField(default=0),
        ),
    ]
