# Generated by Django 5.2.9 on 2025-12-08 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_last_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('test_type', models.CharField(choices=[('basic', 'Análisis Básico'), ('numerology', 'Numerología Completa'), ('compatibility', 'Compatibilidad de Pareja'), ('career', 'Orientación Profesional'), ('spiritual', 'Camino Espiritual'), ('health', 'Salud y Bienestar'), ('financial', 'Abundancia Financiera'), ('family', 'Relaciones Familiares'), ('purpose', 'Propósito de Vida'), ('past_life', 'Vidas Pasadas')], max_length=50)),
                ('required_access_level', models.CharField(choices=[('free', 'Gratuito'), ('personal', 'Personal'), ('professional', 'Profesional'), ('premium', 'Premium')], default='personal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('available_for_therapists', models.BooleanField(default=True)),
                ('available_for_personal', models.BooleanField(default=True)),
                ('uses_per_month', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('estimated_duration', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Módulo de Test',
                'verbose_name_plural': 'Módulos de Tests',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.testmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de Test',
                'verbose_name_plural': 'Resultados de Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('current_month_uses', models.IntegerField(default=0)),
                ('month_reset_date', models.DateField(auto_now_add=True)),
                ('has_special_access', models.BooleanField(default=False)),
                ('special_access_expires', models.DateTimeField(blank=True, null=True)),
                ('special_access_uses', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='api.testmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a Test',
                'verbose_name_plural': 'Accesos a Tests',
                'unique_together': {('user', 'test_module')},
            },
        ),
    ]
