# Generated by Django 5.2.9 on 2025-12-08 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_testmodule_testresult_usertestaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBirthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nombre completo según documento', max_length=200)),
                ('birth_date', models.DateField(help_text='Fecha de nacimiento')),
                ('birth_time', models.TimeField(blank=True, help_text='Hora de nacimiento (opcional)', null=True)),
                ('birth_city', models.CharField(blank=True, help_text='Ciudad de nacimiento', max_length=200)),
                ('birth_country', models.CharField(blank=True, help_text='País de nacimiento', max_length=100)),
                ('birth_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del lugar de nacimiento', max_digits=9, null=True)),
                ('birth_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del lugar de nacimiento', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Si está bloqueado, el usuario no puede cambiar estos datos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos de Nacimiento',
                'verbose_name_plural': 'Datos de Nacimiento',
            },
        ),
    ]
