# Generated by Django 5.2.9 on 2025-12-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_userbirthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbirthdata',
            name='unlock_requested',
            field=models.BooleanField(default=False, help_text='Se ha solicitado desbloqueo'),
        ),
        migrations.AddField(
            model_name='userbirthdata',
            name='unlock_token',
            field=models.CharField(blank=True, help_text='Token para desbloquear por email', max_length=128, null=True),
        ),
    ]
