# Generated by Django 5.2.9 on 2025-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_unlock_fields_to_birthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodule',
            name='test_type',
            field=models.CharField(choices=[('basic', 'Análisis Básico'), ('numerology', 'Numerología Completa'), ('compatibility', 'Compatibilidad de Pareja'), ('career', 'Orientación Profesional'), ('spiritual', 'Camino Espiritual'), ('health', 'Salud y Bienestar'), ('financial', 'Abundancia Financiera'), ('family', 'Relaciones Familiares'), ('purpose', 'Propósito de Vida'), ('past_life', 'Vidas Pasadas'), ('pai', 'PAI - Inventario de Personalidad')], max_length=50),
        ),
    ]
