# Generated by Django 5.2.9 on 2025-12-09 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_pai_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodule',
            name='license_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testmodule',
            name='requires_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='test_type',
            field=models.CharField(choices=[('basic', 'Análisis Básico'), ('numerology', 'Numerología Completa'), ('compatibility', 'Compatibilidad de Pareja'), ('career', 'Orientación Profesional'), ('spiritual', 'Camino Espiritual'), ('health', 'Salud y Bienestar'), ('financial', 'Abundancia Financiera'), ('family', 'Relaciones Familiares'), ('purpose', 'Propósito de Vida'), ('past_life', 'Vidas Pasadas'), ('pai', 'PAI - Inventario de Personalidad'), ('bdi', 'BDI-II - Inventario de Depresión de Beck'), ('bai', 'BAI - Inventario de Ansiedad de Beck'), ('diagnostic', 'Diagnostic Screenings (PHQ/GAD/Other)')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserTestLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_licenses', to=settings.AUTH_USER_MODEL)),
                ('test_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='api.testmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licencia de Test',
                'verbose_name_plural': 'Licencias de Tests',
                'unique_together': {('user', 'test_module')},
            },
        ),
    ]
