# Generated by Django 5.2.9 on 2025-12-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_testmodule_license_info_testmodule_requires_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Paciente asociado a este test (si fue ejecutado por un terapeuta)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='api.patient'),
        ),
    ]
