# Generated by Django 5.2.9 on 2025-12-11 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_configure_admin_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('therapist', 'email')},
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario asociado si el paciente tiene cuenta de login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='angel_remedy',
            field=models.CharField(blank=True, help_text="Ángel remedio (ej: 'Caliel', 'Veuliah', 'Mikael')", max_length=100),
        ),
        migrations.AddField(
            model_name='testresult',
            name='clinical_diagnosis',
            field=models.CharField(blank=True, help_text="Diagnóstico clínico (ej: 'Ansiedad Severa', 'Depresión Moderada')", max_length=255),
        ),
        migrations.AddField(
            model_name='testresult',
            name='details',
            field=models.JSONField(blank=True, help_text='Respuestas crudas, análisis completo u otros datos adicionales', null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='kabbalah_sefira',
            field=models.CharField(blank=True, help_text="Sefirá relacionada (ej: 'Netzach', 'Malchut', 'Binah')", max_length=100),
        ),
        migrations.AddField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(blank=True, help_text='Puntaje numérico del test psicométrico', null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_id',
            field=models.CharField(blank=True, help_text="ID del test psicométrico (ej: 'phq-9', 'gad-7', 'ptsd', 'scl-90-r', etc.)", max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='therapist',
            field=models.ForeignKey(help_text='Terapeuta que creó y gestiona este paciente', limit_choices_to={'profile__user_type': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='input_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.testmodule'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('personal', 'Usuario Personal'), ('therapist', 'Terapeuta Profesional'), ('patient', 'Paciente'), ('visitor', 'Visitante')], default='personal', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('therapist', 'email'), ('therapist', 'user')},
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['test_id', 'created_at'], name='api_testres_test_id_5ac0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['user', 'created_at'], name='api_testres_user_id_1abd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['patient', 'created_at'], name='api_testres_patient_ca6c2a_idx'),
        ),
    ]
