# Generated by Django 5.2.9 on 2025-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_patient_unique_together_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL del avatar del paciente'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Lugar de nacimiento (ciudad, país)', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_time',
            field=models.TimeField(blank=True, help_text='Hora exacta de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_history',
            field=models.TextField(blank=True, help_text='Historial clínico del paciente'),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, help_text='Nombre del paciente', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='hebrew_name',
            field=models.CharField(blank=True, help_text='Nombre en hebreo (opcional)', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, help_text='Apellidos del paciente', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='main_complaint',
            field=models.TextField(blank=True, help_text='Motivo principal de consulta'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_plan',
            field=models.JSONField(blank=True, default=dict, help_text='Plan de tratamiento holístico en formato JSON: { "meditations": [], "oils": [], "magnetism": [], "biodecoding": [] }'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(help_text='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(help_text='Email del paciente', max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(help_text='Nombre completo (calculado automáticamente)', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el paciente está activo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales del terapeuta'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20),
        ),
    ]
