# Generated by Django 5.2.9 on 2025-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_holistic_patient_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='therapy_level',
            field=models.CharField(blank=True, choices=[('assiyah', 'Nivel 1: Sanación (Assiyah)'), ('yetzirah', 'Nivel 2: Equilibrio (Yetzirah)'), ('beriah', 'Nivel 3: Propósito (Beriah)')], help_text='Nivel de terapia cabalística en el que se está trabajando con el paciente', max_length=20, null=True),
        ),
    ]
