# Generated by Django 5.2.9 on 2025-12-12 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_therapy_level_to_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabalisticAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('gematria', 'Gematria'), ('tarot', 'Tarot Terapéutico'), ('soul-map', 'Mapa del Alma'), ('astrology', 'Carta Astral Cabalística'), ('tikun', 'Análisis de Tikún')], help_text='Tipo de análisis cabalístico realizado', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Datos de entrada del análisis (ej: palabra para Gematria, fecha para Tarot)')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Resultados completos del análisis en formato JSON')),
                ('summary', models.TextField(blank=True, help_text='Resumen breve del análisis para visualización rápida')),
                ('therapist_notes', models.TextField(blank=True, help_text='Notas adicionales del terapeuta sobre este análisis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Paciente para el que se realizó el análisis', on_delete=django.db.models.deletion.CASCADE, related_name='cabalistic_analyses', to='api.patient')),
                ('therapist', models.ForeignKey(help_text='Terapeuta que ejecutó el análisis', on_delete=django.db.models.deletion.CASCADE, related_name='cabalistic_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis Cabalístico',
                'verbose_name_plural': 'Análisis Cabalísticos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'analysis_type', '-created_at'], name='api_cabalis_patient_9d1192_idx'), models.Index(fields=['therapist', '-created_at'], name='api_cabalis_therapi_be0633_idx')],
            },
        ),
    ]
