# Generated by Django 5.2.9 on 2025-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_shekinah_analysis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabalisticanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('gematria', 'Gematria'), ('tarot', 'Tarot Terapéutico'), ('soul-map', 'Mapa del Alma'), ('astrology', 'Carta Astral Cabalística'), ('tikun', 'Análisis de Tikún'), ('shekinah', 'Análisis Shejinah Moderno Pitagórico'), ('astrology-kerykeion', 'Astrología Técnica (Kerykeion)')], help_text='Tipo de análisis cabalístico realizado', max_length=20),
        ),
    ]
