# Generated by Django 5.2.9 on 2025-12-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_crossover_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_city',
            field=models.CharField(blank=True, help_text='Ciudad de nacimiento', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_country',
            field=models.CharField(blank=True, help_text='País de nacimiento', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del lugar de nacimiento', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del lugar de nacimiento', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_timezone',
            field=models.CharField(blank=True, help_text='Zona horaria del lugar de nacimiento', max_length=100),
        ),
    ]
