# Generated by Django 5.2.9 on 2025-12-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_patient_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbirthdata',
            name='birth_place_label',
            field=models.CharField(blank=True, help_text="Etiqueta formateada del lugar de nacimiento (ej: 'La Habana, Cuba')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userbirthdata',
            name='full_name_change_count',
            field=models.IntegerField(default=0, help_text='Número de veces que se ha cambiado el nombre completo'),
        ),
        migrations.AddField(
            model_name='userbirthdata',
            name='full_name_locked',
            field=models.BooleanField(default=False, help_text='Si está bloqueado, el usuario no puede cambiar el nombre completo'),
        ),
    ]
