# Generated by Django 5.2.9 on 2025-12-15 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_name_change_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estable de la ejecución de análisis (UUID).', primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('clinical_test', 'Clinical Test'), ('kabbalah', 'Kabbalah'), ('astrology', 'Astrology'), ('legacy', 'Legacy')], help_text='Tipo de análisis ejecutado.', max_length=32)),
                ('module_code', models.CharField(help_text='Identificador estable del módulo (ej: PHQ9, SCDF, KERYKEION_NATAL).', max_length=64)),
                ('role_context', models.CharField(choices=[('therapist', 'Therapist'), ('personal', 'Personal'), ('patient', 'Patient')], help_text='Contexto de rol en el momento de la ejecución.', max_length=16)),
                ('execution_mode', models.CharField(blank=True, choices=[('patient_self', 'Patient Self'), ('therapist_clinical', 'Therapist Clinical')], help_text='Derivado en backend desde module_code + contexto. Nunca confiado desde request.', max_length=32, null=True)),
                ('birth_data_snapshot', models.JSONField(help_text='Snapshot inmutable de datos de nacimiento en el momento del análisis. Debe incluir: legal_name, birth_date, birth_time, city, country, lat, lng, timezone, geocode_source.')),
                ('algorithm_snapshot', models.JSONField(help_text='Snapshot inmutable de motor/versión/parámetros. Campos esperados: engine, version, build_hash (opcional), params.')),
                ('raw_input', models.JSONField(blank=True, help_text='Input crudo recibido desde frontend / capa de orquestación.', null=True)),
                ('computed_result', models.JSONField(blank=True, help_text='Resultado normalizado final del análisis (JSON).', null=True)),
                ('legacy_output', models.JSONField(blank=True, help_text='Salida original del módulo legacy (JSON serializado, opcional).', null=True)),
                ('visibility', models.CharField(choices=[('therapist', 'Therapist only'), ('patient', 'Patient only'), ('both', 'Therapist and Patient')], default='therapist', help_text='Quién puede ver este AnalysisRecord en dashboards.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabalistic_analysis', models.ForeignKey(blank=True, help_text='Análisis cabalístico relacionado, si existe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_records', to='api.cabalisticanalysis')),
                ('created_by_user', models.ForeignKey(help_text='Usuario que dispara la ejecución (terapeuta, personal o paciente).', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_created_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, help_text='Paciente clínico asociado (obligatorio en therapist_clinical).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_records', to='api.patient')),
                ('subject_user', models.ForeignKey(blank=True, help_text='Usuario sujeto del análisis (si existe cuenta).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_subject_records', to=settings.AUTH_USER_MODEL)),
                ('test_result', models.ForeignKey(blank=True, help_text='Resultado de test relacionado, si existe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_records', to='api.testresult')),
                ('therapist', models.ForeignKey(blank=True, help_text='Terapeuta propietario (ownership clínico).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_analysis_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Record',
                'verbose_name_plural': 'Analysis Records',
                'indexes': [models.Index(fields=['subject_user', 'created_at'], name='api_analysi_subject_05aeed_idx'), models.Index(fields=['created_by_user', 'created_at'], name='api_analysi_created_cac56c_idx'), models.Index(fields=['kind', 'module_code'], name='api_analysi_kind_a20a7b_idx'), models.Index(fields=['created_at'], name='api_analysi_created_624740_idx')],
            },
        ),
    ]
