# Generated by Django 5.2.9 on 2025-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_analysisrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del lugar de nacimiento (núcleo perfil)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del lugar de nacimiento (núcleo perfil)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_timezone',
            field=models.CharField(blank=True, help_text='Zona horaria del lugar de nacimiento (núcleo perfil)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Marca de tiempo de aceptación de consentimiento terapéutico', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name_change_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_version',
            field=models.IntegerField(default=1),
        ),
    ]
