# Generated by Django 5.2.9 on 2025-12-15 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_userprofile_birth_city_userprofile_birth_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título del recurso', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del recurso')),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('course', 'Curso')], help_text='Tipo de recurso', max_length=20)),
                ('content_url', models.URLField(blank=True, help_text='URL del contenido del recurso')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL de la miniatura')),
                ('access_level', models.CharField(default='free', help_text='Nivel de acceso base (free, personal, professional, premium)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el recurso está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResourceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('free', 'Gratuito'), ('assigned_by_therapist', 'Asignado por terapeuta'), ('self_purchased', 'Auto-adquirido')], help_text='Origen del acceso', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Terapeuta que asignó el recurso (solo si source=assigned_by_therapist)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_resources', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(help_text='Recurso al que se tiene acceso', on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='api.resource')),
                ('user', models.ForeignKey(help_text='Usuario que tiene acceso al recurso', on_delete=django.db.models.deletion.CASCADE, related_name='resource_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a Recurso',
                'verbose_name_plural': 'Accesos a Recursos',
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_userres_user_id_34ec3e_idx'), models.Index(fields=['resource', 'source'], name='api_userres_resourc_7f2b97_idx')],
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
