# Generated by Django 5.2.9 on 2025-12-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_resource_access_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='therapist_annotations',
            field=models.JSONField(blank=True, default=dict, help_text='Anotaciones del terapeuta sobre este resultado. Estructura: {summary: string, notes: string, visible_to_patient: boolean}. Editable solo por el terapeuta propietario.', null=True),
        ),
    ]
