# Generated by Django 5.2.9 on 2025-12-17 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_therapist_annotations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioEmotionalDictionaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrada de diccionario bio-emocional',
                'verbose_name_plural': 'Diccionario bio-emocional',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='userresourceaccess',
            name='resource',
        ),
        migrations.AlterUniqueTogether(
            name='userresourceaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userresourceaccess',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userresourceaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='therapist_annotations',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_country',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_latitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_longitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_timezone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_longitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_timezone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='consent_accepted_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='legal_full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name_change_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_version',
        ),
        migrations.AlterField(
            model_name='cabalisticanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('gematria', 'Gematria'), ('tarot', 'Tarot Terapéutico'), ('soul-map', 'Mapa del Alma'), ('astrology', 'Carta Astral Cabalística'), ('tikun', 'Análisis de Tikún')], help_text='Tipo de análisis cabalístico realizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BioTransgenerationalHypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('termino_bioemocional', models.CharField(max_length=255)),
                ('hypothesis_type', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Hipótesis terapéutica en exploración (no diagnóstico).')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_review', 'En revisión'), ('discarded', 'Descartada')], default='open', max_length=16)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_hypotheses', to='api.patient')),
                ('therapist', models.ForeignKey(help_text='Terapeuta autor de la hipótesis', on_delete=django.db.models.deletion.CASCADE, related_name='bio_hypotheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hipótesis bio-transgeneracional',
                'verbose_name_plural': 'Hipótesis bio-transgeneracionales',
                'ordering': ['patient', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenealogyPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.IntegerField(help_text='0=paciente, -1=padres, -2=abuelos, etc.')),
                ('relation', models.CharField(help_text='Relación con el paciente (madre, padre, abuelo materno, etc.)', max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_people', to='api.patient')),
            ],
            options={
                'verbose_name': 'Persona del árbol transgeneracional',
                'verbose_name_plural': 'Personas del árbol transgeneracional',
                'ordering': ['patient', 'generation', 'relation'],
            },
        ),
        migrations.CreateModel(
            name='GenealogyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_events', to='api.patient')),
                ('linked_people', models.ManyToManyField(blank=True, related_name='linked_events', to='api.genealogyperson')),
            ],
            options={
                'verbose_name': 'Evento transgeneracional',
                'verbose_name_plural': 'Eventos transgeneracionales',
                'ordering': ['patient', '-year', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='UserResourceAccess',
        ),
        migrations.AddIndex(
            model_name='biotransgenerationalhypothesis',
            index=models.Index(fields=['patient', 'status'], name='api_biotran_patient_2358dc_idx'),
        ),
        migrations.AddIndex(
            model_name='genealogyperson',
            index=models.Index(fields=['patient', 'generation'], name='api_genealo_patient_24d261_idx'),
        ),
        migrations.AddIndex(
            model_name='genealogyevent',
            index=models.Index(fields=['patient', 'year'], name='api_genealo_patient_57a85d_idx'),
        ),
    ]
