# Generated by Django 5.2.9 on 2025-12-23 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_bioemotionaldictionaryentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioEmotionalHypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('related_region_id', models.CharField(blank=True, max_length=64, null=True)),
                ('related_dictionary_term', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_review', 'En revisi¢n'), ('discarded', 'Descartada')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_hypotheses', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_hypotheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hip¢tesis bio-emocional',
                'verbose_name_plural': 'Hip¢tesis bio-emocionales',
                'ordering': ['patient', '-updated_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='api_bioemot_patient_0a2fd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='BioEmotionalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_id', models.CharField(blank=True, max_length=64, null=True)),
                ('dictionary_term_slug', models.CharField(blank=True, max_length=128, null=True)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_observations', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observaci¢n bio-emocional',
                'verbose_name_plural': 'Observaciones bio-emocionales',
                'ordering': ['patient', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='api_bioemot_patient_e1bd31_idx')],
            },
        ),
    ]
