# Generated by Django 5.2.9 on 2025-12-23 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_bioemotionalhypothesis_bioemotionalobservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioEmotionalSynthesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_synthesis', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_synthesis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sintesis bio-emocional',
                'verbose_name_plural': 'Sintesis bio-emocionales',
                'ordering': ['patient', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_closed'], name='api_bioemot_patient_ec0e18_idx')],
            },
        ),
    ]
