# Generated by Django 5.2.9 on 2025-12-23 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_bioemotionalsynthesis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioEmotionalAssistedDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('based_on', models.JSONField(blank=True, default=list)),
                ('prompt_version', models.CharField(max_length=64)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_assisted_diagnoses', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_assisted_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura asistida bio-emocional',
                'verbose_name_plural': 'Lecturas asistidas bio-emocionales',
                'ordering': ['patient', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_validated'], name='api_bioemot_patient_2419c7_idx')],
            },
        ),
    ]
