# Generated by Django 5.2.9 on 2025-12-23 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_bioemotionalassisteddiagnosis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioEmotionalPatientBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_patient_briefs', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_patient_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen bio-emocional para paciente',
                'verbose_name_plural': 'Resúmenes bio-emocionales para paciente',
                'ordering': ['patient', '-updated_at'],
                'indexes': [models.Index(fields=['patient', 'is_published'], name='api_bioemot_patient_2f998f_idx')],
            },
        ),
    ]
