# Generated by Django 5.2.9 on 2025-12-23 21:45

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_bioemotionalpatientbrief'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyNatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de cuándo se realizó el cálculo')),
                ('house_system', models.CharField(default='placidus', help_text='Sistema de casas usado (placidus, koch, etc.)', max_length=50)),
                ('source', models.CharField(default='kerykeion', help_text='Motor usado para el cálculo (kerykeion, swisseph, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('ok', 'Cálculo exitoso'), ('error', 'Error en cálculo')], default='ok', help_text='Estado del cálculo', max_length=20)),
                ('chart_payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Carta natal en formato normalizado estable')),
                ('input_snapshot', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Snapshot de los datos de entrada usados (fecha/hora/coords del perfil)', null=True)),
                ('error_payload', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Detalle del error si el cálculo falló', null=True)),
                ('created_by', models.ForeignKey(help_text='Terapeuta que generó este cálculo', on_delete=django.db.models.deletion.CASCADE, related_name='astrology_charts_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(help_text='Paciente al que pertenece esta carta natal', on_delete=django.db.models.deletion.CASCADE, related_name='natal_chart_kerykeion', to='api.patient')),
            ],
            options={
                'verbose_name': 'Carta Natal (Astrología)',
                'verbose_name_plural': 'Cartas Natales (Astrología)',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
