# Generated by Django 5.2.9 on 2025-12-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_repair_analysisrecord_therapist_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='therapist_annotations',
            field=models.JSONField(blank=True, default=dict, help_text='Anotaciones del terapeuta sobre este resultado. Estructura: {summary: string, notes: string, visible_to_patient: boolean}.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='biological_sex',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('intersex', 'Intersexual'), ('unknown', 'Desconocido'), ('not_recorded', 'Sin registro')], default='not_recorded', help_text='Sexo biológico (demografía básica)', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('woman', 'Mujer'), ('man', 'Hombre'), ('non_binary', 'No binaria'), ('other', 'Otra'), ('prefer_not_to_say', 'Prefiere no decirlo'), ('not_recorded', 'Sin registro')], default='not_recorded', help_text='Identidad de género (demografía básica)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biological_sex',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('intersex', 'Intersexual'), ('unknown', 'Desconocido'), ('not_recorded', 'Sin registro')], default='not_recorded', help_text='Sexo biológico (demografía básica)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('woman', 'Mujer'), ('man', 'Hombre'), ('non_binary', 'No binaria'), ('other', 'Otra'), ('prefer_not_to_say', 'Prefiere no decirlo'), ('not_recorded', 'Sin registro')], default='not_recorded', help_text='Identidad de género (demografía básica)', max_length=20),
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='test_type',
            field=models.CharField(choices=[('basic', 'Análisis Básico'), ('numerology', 'Numerología Completa'), ('compatibility', 'Compatibilidad de Pareja'), ('career', 'Orientación Profesional'), ('spiritual', 'Camino Espiritual'), ('health', 'Salud y Bienestar'), ('financial', 'Abundancia Financiera'), ('family', 'Relaciones Familiares'), ('purpose', 'Propósito de Vida'), ('past_life', 'Vidas Pasadas'), ('pai', 'PAI - Inventario de Personalidad'), ('bdi', 'BDI-II - Inventario de Depresión de Beck'), ('bai', 'BAI - Inventario de Ansiedad de Beck'), ('diagnostic', 'Diagnostic Screenings (PHQ/GAD/Other)'), ('holistic_screening', 'Holistic Screenings (in-house)')], max_length=50),
        ),
    ]
