# Generated by Django 5.2.9 on 2025-12-26

from django.db import migrations


def create_past_lives_test(apps, schema_editor):
    TestModule = apps.get_model('api', 'TestModule')

    description = (
        'Exploración personal y simbólica orientada a la reflexión sobre patrones, emociones y sentido vital.\n\n'
        'DISCLAIMER (obligatorio antes de iniciar):\n'
        'Este cuestionario es una herramienta de exploración personal y simbólica.\n'
        'No constituye diagnóstico médico ni psicológico ni afirma hechos históricos literales.\n'
        'Su finalidad es facilitar conciencia, reflexión e integración emocional.'
    )

    TestModule.objects.update_or_create(
        code='past-lives',
        defaults={
            'name': 'Vidas Pasadas – Exploración de Memorias del Alma',
            'description': description,
            'test_type': 'holistic_screening',
            'is_active': True,
            # Visible to therapists, executable as patient_self (patient/personal) via backend rules.
            # We keep available_for_personal=True so it can be assigned and shown to patients.
            'available_for_therapists': True,
            'available_for_personal': True,
            'required_access_level': 'premium',
            'requires_license': False,
            'license_info': '',
            'uses_per_month': None,
            'estimated_duration': 12,
            'order': 0,
        },
    )


def remove_past_lives_test(apps, schema_editor):
    TestModule = apps.get_model('api', 'TestModule')
    TestModule.objects.filter(code='past-lives').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_analysisrecord_therapist_annotations_and_more'),
    ]

    operations = [
        migrations.RunPython(create_past_lives_test, remove_past_lives_test),
    ]
