# Generated by Django 5.2.9 on 2025-12-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_past_lives_testmodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrecord',
            name='kind',
            field=models.CharField(choices=[('clinical_test', 'Clinical Test'), ('kabbalah', 'Kabbalah'), ('astrology', 'Astrology'), ('legacy', 'Legacy'), ('holistic_evaluative_synthesis', 'Holistic Evaluative Synthesis')], help_text='Tipo de análisis ejecutado.', max_length=32),
        ),
        migrations.CreateModel(
            name='TherapistHolisticConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(default=dict, help_text='Pesos por disciplina: {"kabbalah_numerology": 0.20, "tarot_evolutivo": 0.20, "astrologia_terapeutica": 0.20, "transgeneracional": 0.20, "biodecodificacion": 0.20}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.OneToOneField(help_text='Terapeuta propietario de esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='holistic_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración Holística del Terapeuta',
                'verbose_name_plural': 'Configuraciones Holísticas de Terapeutas',
            },
        ),
    ]
