# Generated by Django 5.2.9 on 2025-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_add_msme_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistholisticconfig',
            name='weights',
            field=models.JSONField(default=dict, help_text='Pesos para cada módulo holístico (deben sumar 1.0)'),
        ),
    ]
