# Generated by Django 5.2.9 on 2025-12-30 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_therapistholisticconfig_weights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResonanciaObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('resonancia', 'Resonancia'), ('eje', 'Eje'), ('repeticion', 'Repetición'), ('nota', 'Nota')], max_length=16)),
                ('source', models.CharField(choices=[('observacion_directa', 'Observación directa'), ('registro_manual', 'Registro manual')], default='registro_manual', max_length=32)),
                ('context', models.CharField(choices=[('familiar', 'Familiar'), ('relacional', 'Relacional'), ('sistemico', 'Sistémico')], max_length=16)),
                ('state', models.CharField(choices=[('activo', 'Activo'), ('latente', 'Latente')], max_length=16)),
                ('anchors', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('statement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'profile__user_type': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='resonancia_observations', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonancia_observations', to='api.patient')),
            ],
            options={
                'verbose_name': 'Observación (Resonancia)',
                'verbose_name_plural': 'Observaciones (Resonancia)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', '-created_at'], name='res_subj_created_idx'), models.Index(fields=['author', '-created_at'], name='res_auth_created_idx')],
            },
        ),
    ]
