# Generated by Django 5.2.9 on 2026-01-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_reclassify_testmodules'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolisticExploration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('public_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('primary_sefirah', models.CharField(max_length=32)),
                ('secondary_sefirot', models.JSONField(blank=True, default=list)),
                ('therapist_only_results', models.BooleanField(default=True)),
                ('ai_interpretation_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holistic_explorations', to='api.testmodule')),
            ],
        ),
    ]
