# Generated by Django 5.2.9 on 2026-01-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_add_holistic_exploration'),
    ]

    operations = [
        migrations.AddField(
            model_name='holisticexploration',
            name='client_visible_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='holisticexploration',
            name='therapist_only_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
