# Generated by Django 5.2.9 on 2026-01-14 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_add_holistic_exploration_visibility_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodule',
            name='public_name',
            field=models.CharField(blank=True, help_text='Nombre amigable visible en UI (sin nomenclatura clínica).', max_length=255),
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='test_type',
            field=models.CharField(choices=[('basic', 'Análisis Básico'), ('numerology', 'Numerología Completa'), ('compatibility', 'Compatibilidad de Pareja'), ('career', 'Orientación Profesional'), ('spiritual', 'Camino Espiritual'), ('health', 'Salud y Bienestar'), ('financial', 'Abundancia Financiera'), ('family', 'Relaciones Familiares'), ('purpose', 'Propósito de Vida'), ('past_life', 'Vidas Pasadas'), ('pai', 'PAI - Inventario de Personalidad'), ('bdi', 'BDI-II - Inventario de Depresión de Beck'), ('bai', 'BAI - Inventario de Ansiedad de Beck'), ('diagnostic', 'Diagnostic Screenings (PHQ/GAD/Other)'), ('holistic_screening', 'Holistic Screenings (in-house)'), ('wellness', 'Wellness (in-house)')], max_length=50),
        ),
    ]
