# Generated by Django 5.2.9 on 2026-01-14 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_testmodule_public_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionConfig',
            fields=[
                ('dimension_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('world', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('sefirah', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('items_required', models.IntegerField(help_text='Number of questions to include per test')),
            ],
            options={
                'db_table': 'mcmi4_mystic_dimension_config',
                'ordering': ['world', 'dimension_id'],
            },
        ),
        migrations.CreateModel(
            name='MCMI4MysticQuestionBank',
            fields=[
                ('question_id', models.CharField(help_text='Unique ID (e.g., atz_ktr_001)', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('world', models.CharField(choices=[('atzilut', 'Atzilut - Emanativo/Espiritual'), ('briah', 'Briah - Creativo/Intelectual'), ('yetzirah', 'Yetzirah - Formativo/Emocional'), ('assiah', 'Assiah - Material/Físico')], db_index=True, max_length=20)),
                ('dimension_id', models.CharField(db_index=True, help_text='Dimension identifier (e.g., atzilut_keter_purpose)', max_length=50)),
                ('sefirah', models.CharField(choices=[('keter', 'Keter'), ('chochmah', 'Chochmah'), ('binah', 'Binah'), ('chesed', 'Chesed'), ('gevurah', 'Gevurah'), ('tiferet', 'Tiferet'), ('netzach', 'Netzach'), ('hod', 'Hod'), ('yesod', 'Yesod'), ('malkhut', 'Malkhut'), ('multiple', 'Multiple')], max_length=20)),
                ('text_es', models.TextField(help_text='Question text in Spanish')),
                ('text_en', models.TextField(blank=True, help_text='Question text in English (optional)')),
                ('reverse_scored', models.BooleanField(default=False, help_text='If True, response is inverted (3-response)')),
                ('weight', models.FloatField(default=1.0, help_text='Weight for this item in scoring', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text="If False, question won't be selected")),
            ],
            options={
                'db_table': 'mcmi4_mystic_question_bank',
                'ordering': ['world', 'dimension_id', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='MCMI4MysticTestInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('questions_used', models.JSONField(help_text='List of question_ids selected for this test')),
                ('responses', models.JSONField(default=dict, help_text='Patient responses {question_id: response_value}')),
                ('raw_scores', models.JSONField(blank=True, help_text='Raw scores by dimension and world', null=True)),
                ('structured_data', models.JSONField(blank=True, help_text='Full structured results with interpretations', null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mcmi4_mystic_test_instance',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='astrologynatalchart',
                            name='created_by',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='astrologynatalchart',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalassisteddiagnosis',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalassisteddiagnosis',
                            name='therapist',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='BioEmotionalDictionaryEntry',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalhypothesis',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalhypothesis',
                            name='therapist',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalobservation',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalobservation',
                            name='therapist',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalpatientbrief',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalpatientbrief',
                            name='therapist',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalsynthesis',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='bioemotionalsynthesis',
                            name='therapist',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='biotransgenerationalhypothesis',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='biotransgenerationalhypothesis',
                            name='therapist',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='genealogyevent',
                            name='linked_people',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='genealogyevent',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='genealogyperson',
                            name='patient',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='userbirthdata',
                            name='updated_by',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='userbirthdata',
                            name='user',
                        ),
            ],
        ),
        migrations.AddIndex(
            model_name='mcmi4mysticquestionbank',
            index=models.Index(fields=['world', 'dimension_id'], name='mcmi4_mysti_world_a4fbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='mcmi4mysticquestionbank',
            index=models.Index(fields=['dimension_id'], name='mcmi4_mysti_dimensi_fce670_idx'),
        ),
        migrations.AddField(
            model_name='mcmi4mystictestinstance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcmi4_mystic_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='AstrologyNatalChart',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='BioEmotionalAssistedDiagnosis',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='BioEmotionalHypothesis',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='BioEmotionalObservation',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='BioEmotionalPatientBrief',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='BioEmotionalSynthesis',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='BioTransgenerationalHypothesis',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='GenealogyEvent',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='GenealogyPerson',
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.DeleteModel(
                            name='UserBirthData',
                        ),
            ],
        ),
        migrations.AddIndex(
            model_name='mcmi4mystictestinstance',
            index=models.Index(fields=['patient', '-applied_at'], name='mcmi4_mysti_patient_1abe3f_idx'),
        ),
    ]
