# Generated by Django 5.2.9 on 2026-01-14 15:47

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_mcmi4_mystic_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='BioEmotionalDictionaryEntry',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('slug', models.SlugField(max_length=128, unique=True)),
                                ('title', models.CharField(max_length=255)),
                                ('category', models.CharField(blank=True, max_length=128)),
                                ('description', models.TextField(blank=True)),
                                ('tags', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=255)),
                                ('is_active', models.BooleanField(default=True)),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('updated_at', models.DateTimeField(auto_now=True)),
                            ],
                            options={
                                'verbose_name': 'Entrada de diccionario bio-emocional',
                                'verbose_name_plural': 'Diccionario bio-emocional',
                                'ordering': ['category', 'title'],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='AstrologyNatalChart',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de cuándo se realizó el cálculo')),
                                ('house_system', models.CharField(default='placidus', help_text='Sistema de casas usado (placidus, koch, etc.)', max_length=50)),
                                ('source', models.CharField(default='kerykeion', help_text='Motor usado para el cálculo (kerykeion, swisseph, etc.)', max_length=50)),
                                ('status', models.CharField(choices=[('ok', 'Cálculo exitoso'), ('error', 'Error en cálculo')], default='ok', help_text='Estado del cálculo', max_length=20)),
                                ('chart_payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Carta natal en formato normalizado estable')),
                                ('input_snapshot', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Snapshot de los datos de entrada usados (fecha/hora/coords del perfil)', null=True)),
                                ('error_payload', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Detalle del error si el cálculo falló', null=True)),
                                ('created_by', models.ForeignKey(help_text='Terapeuta que generó este cálculo', on_delete=django.db.models.deletion.CASCADE, related_name='astrology_charts_created', to=settings.AUTH_USER_MODEL)),
                                ('patient', models.OneToOneField(help_text='Paciente al que pertenece esta carta natal', on_delete=django.db.models.deletion.CASCADE, related_name='natal_chart_kerykeion', to='api.patient')),
                            ],
                            options={
                                'verbose_name': 'Carta Natal (Astrología)',
                                'verbose_name_plural': 'Cartas Natales (Astrología)',
                                'ordering': ['-calculated_at'],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='GenealogyPerson',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('generation', models.IntegerField(help_text='0=paciente, -1=padres, -2=abuelos, etc.')),
                                ('relation', models.CharField(help_text='Relación con el paciente (madre, padre, abuelo materno, etc.)', max_length=128)),
                                ('name', models.CharField(blank=True, max_length=255)),
                                ('birth_year', models.IntegerField(blank=True, null=True)),
                                ('death_year', models.IntegerField(blank=True, null=True)),
                                ('notes', models.TextField(blank=True)),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('updated_at', models.DateTimeField(auto_now=True)),
                                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_people', to='api.patient')),
                            ],
                            options={
                                'verbose_name': 'Persona del árbol transgeneracional',
                                'verbose_name_plural': 'Personas del árbol transgeneracional',
                                'ordering': ['patient', 'generation', 'relation'],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='GenealogyEvent',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('title', models.CharField(max_length=255)),
                                ('year', models.IntegerField(blank=True, null=True)),
                                ('description', models.TextField(blank=True)),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('updated_at', models.DateTimeField(auto_now=True)),
                                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_events', to='api.patient')),
                                ('linked_people', models.ManyToManyField(blank=True, related_name='linked_events', to='api.genealogyperson')),
                            ],
                            options={
                                'verbose_name': 'Evento transgeneracional',
                                'verbose_name_plural': 'Eventos transgeneracionales',
                                'ordering': ['patient', '-year', 'title'],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='UserBirthData',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('full_name', models.CharField(help_text='Nombre completo según documento', max_length=200)),
                                ('birth_date', models.DateField(help_text='Fecha de nacimiento')),
                                ('birth_time', models.TimeField(blank=True, help_text='Hora de nacimiento (opcional)', null=True)),
                                ('birth_city', models.CharField(blank=True, help_text='Ciudad de nacimiento', max_length=200)),
                                ('birth_country', models.CharField(blank=True, help_text='País de nacimiento', max_length=100)),
                                ('birth_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del lugar de nacimiento', max_digits=9, null=True)),
                                ('birth_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del lugar de nacimiento', max_digits=9, null=True)),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('updated_at', models.DateTimeField(auto_now=True)),
                                ('is_locked', models.BooleanField(default=False, help_text='Si está bloqueado, el usuario no puede cambiar estos datos')),
                                ('unlock_requested', models.BooleanField(default=False, help_text='Se ha solicitado desbloqueo')),
                                ('unlock_token', models.CharField(blank=True, help_text='Token para desbloquear por email', max_length=128, null=True)),
                                ('full_name_change_count', models.IntegerField(default=0, help_text='Número de veces que se ha cambiado el nombre completo')),
                                ('full_name_locked', models.BooleanField(default=False, help_text='Si está bloqueado, el usuario no puede cambiar el nombre completo')),
                                ('birth_place_label', models.CharField(blank=True, help_text="Etiqueta formateada del lugar de nacimiento (ej: 'La Habana, Cuba')", max_length=255, null=True)),
                                ('profile_updated_by_therapist', models.BooleanField(default=False, help_text='Indica si el terapeuta actualizó el perfil para corregir datos')),
                                ('last_therapist_update', models.DateTimeField(blank=True, help_text='Última vez que el terapeuta actualizó el perfil', null=True)),
                                ('updated_by', models.ForeignKey(blank=True, help_text='Terapeuta que actualizó el perfil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_data_updates', to=settings.AUTH_USER_MODEL)),
                                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_data', to=settings.AUTH_USER_MODEL)),
                            ],
                            options={
                                'verbose_name': 'Datos de Nacimiento',
                                'verbose_name_plural': 'Datos de Nacimiento',
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='BioEmotionalAssistedDiagnosis',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('content', models.TextField()),
                                ('based_on', models.JSONField(blank=True, default=list)),
                                ('prompt_version', models.CharField(max_length=64)),
                                ('is_validated', models.BooleanField(default=False)),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('updated_at', models.DateTimeField(auto_now=True)),
                                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_assisted_diagnoses', to='api.patient')),
                                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_assisted_diagnoses', to=settings.AUTH_USER_MODEL)),
                            ],
                            options={
                                'verbose_name': 'Lectura asistida bio-emocional',
                                'verbose_name_plural': 'Lecturas asistidas bio-emocionales',
                                'ordering': ['patient', '-created_at'],
                                'indexes': [models.Index(fields=['patient', 'is_validated'], name='api_bioemot_patient_2419c7_idx')],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='BioEmotionalHypothesis',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('title', models.CharField(max_length=255)),
                                ('description', models.TextField()),
                                ('related_region_id', models.CharField(blank=True, max_length=64, null=True)),
                                ('related_dictionary_term', models.CharField(blank=True, max_length=128, null=True)),
                                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_review', 'En revisi¢n'), ('discarded', 'Descartada')], default='open', max_length=16)),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('updated_at', models.DateTimeField(auto_now=True)),
                                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_hypotheses', to='api.patient')),
                                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_hypotheses', to=settings.AUTH_USER_MODEL)),
                            ],
                            options={
                                'verbose_name': 'Hip¢tesis bio-emocional',
                                'verbose_name_plural': 'Hip¢tesis bio-emocionales',
                                'ordering': ['patient', '-updated_at'],
                                'indexes': [models.Index(fields=['patient', 'status'], name='api_bioemot_patient_0a2fd2_idx')],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='BioEmotionalObservation',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('region_id', models.CharField(blank=True, max_length=64, null=True)),
                                ('dictionary_term_slug', models.CharField(blank=True, max_length=128, null=True)),
                                ('note_text', models.TextField()),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_observations', to='api.patient')),
                                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_observations', to=settings.AUTH_USER_MODEL)),
                            ],
                            options={
                                'verbose_name': 'Observaci¢n bio-emocional',
                                'verbose_name_plural': 'Observaciones bio-emocionales',
                                'ordering': ['patient', '-created_at'],
                                'indexes': [models.Index(fields=['patient', 'created_at'], name='api_bioemot_patient_e1bd31_idx')],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='BioEmotionalPatientBrief',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('title', models.CharField(max_length=255)),
                                ('content', models.TextField()),
                                ('sources', models.JSONField(blank=True, default=list)),
                                ('is_published', models.BooleanField(default=False)),
                                ('published_at', models.DateTimeField(blank=True, null=True)),
                                ('updated_at', models.DateTimeField(auto_now=True)),
                                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_patient_briefs', to='api.patient')),
                                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_patient_briefs', to=settings.AUTH_USER_MODEL)),
                            ],
                            options={
                                'verbose_name': 'Resumen bio-emocional para paciente',
                                'verbose_name_plural': 'Resúmenes bio-emocionales para paciente',
                                'ordering': ['patient', '-updated_at'],
                                'indexes': [models.Index(fields=['patient', 'is_published'], name='api_bioemot_patient_2f998f_idx')],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='BioEmotionalSynthesis',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('text', models.TextField()),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('is_closed', models.BooleanField(default=False)),
                                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_synthesis', to='api.patient')),
                                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_synthesis', to=settings.AUTH_USER_MODEL)),
                            ],
                            options={
                                'verbose_name': 'Sintesis bio-emocional',
                                'verbose_name_plural': 'Sintesis bio-emocionales',
                                'ordering': ['patient', '-created_at'],
                                'indexes': [models.Index(fields=['patient', 'is_closed'], name='api_bioemot_patient_ec0e18_idx')],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='BioTransgenerationalHypothesis',
                            fields=[
                                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                                ('termino_bioemocional', models.CharField(max_length=255)),
                                ('hypothesis_type', models.CharField(max_length=128)),
                                ('description', models.TextField(help_text='Hipótesis terapéutica en exploración (no diagnóstico).')),
                                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_review', 'En revisión'), ('discarded', 'Descartada')], default='open', max_length=16)),
                                ('source_refs', models.JSONField(blank=True, default=dict)),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('updated_at', models.DateTimeField(auto_now=True)),
                                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_hypotheses', to='api.patient')),
                                ('therapist', models.ForeignKey(help_text='Terapeuta autor de la hipótesis', on_delete=django.db.models.deletion.CASCADE, related_name='bio_hypotheses', to=settings.AUTH_USER_MODEL)),
                            ],
                            options={
                                'verbose_name': 'Hipótesis bio-transgeneracional',
                                'verbose_name_plural': 'Hipótesis bio-transgeneracionales',
                                'ordering': ['patient', '-created_at'],
                                'indexes': [models.Index(fields=['patient', 'status'], name='api_biotran_patient_2358dc_idx')],
                            },
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.AddIndex(
                            model_name='genealogyperson',
                            index=models.Index(fields=['patient', 'generation'], name='api_genealo_patient_24d261_idx'),
                        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.AddIndex(
                            model_name='genealogyevent',
                            index=models.Index(fields=['patient', 'year'], name='api_genealo_patient_57a85d_idx'),
                        ),
            ],
        ),
    ]
