# Generated by Django 5.2.9 on 2026-01-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_bioemotionaldictionaryentry_astrologynatalchart_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mcmi4mystictestinstance',
            name='mcmi4_mysti_patient_1abe3f_idx',
        ),
    ]
