# Generated by Django 5.2.9 on 2026-01-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_assignment_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignment',
            new_name='api_assignm_patient_5cb12b_idx',
            old_name='api_assign_patient_test_created_idx',
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='api_assignm_assigne_350bf5_idx',
            old_name='api_assign_assigned_to_created_idx',
        ),
    ]
