# Generated by Django 5.2.9 on 2026-01-20 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_federation_phase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resonanciarelation',
            options={'verbose_name': 'Relación (Resonancia)', 'verbose_name_plural': 'Relaciones (Resonancia)'},
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='assignment_subject_user_required',
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_patient_per_user',
        ),
        migrations.RemoveIndex(
            model_name='resonanciarelation',
            name='resrel_subj_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='resonanciarelation',
            name='resrel_auth_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='resonanciarelation',
            name='resrel_subj_ctx_idx',
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='api_assignm_subject_5eaf11_idx',
            old_name='assignment_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='federationauditlog',
            new_name='api_federat_subject_3b2b84_idx',
            old_name='api_federat_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='federationauditlog',
            new_name='api_federat_request_d8a123_idx',
            old_name='api_federat_request_idx',
        ),
        migrations.RenameIndex(
            model_name='federationauditlog',
            new_name='api_federat_federat_9b7ad9_idx',
            old_name='api_federat_hub_idx',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='clinical_profile',
            field=models.ForeignKey(blank=True, help_text='Perfil clínico opcional (solo en contexto terapéutico)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_assignments', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='(DEPRECATED) Use subject_user + clinical_profile instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject_user',
            field=models.ForeignKey(blank=True, help_text='Usuario sobre el que se ejecuta el análisis (identidad canónica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_as_subject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(help_text='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del lugar de nacimiento', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del lugar de nacimiento', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_time',
            field=models.TimeField(blank=True, help_text='Hora exacta de nacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_timezone',
            field=models.CharField(blank=True, help_text='Zona horaria del lugar de nacimiento', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hebrew_name',
            field=models.CharField(blank=True, help_text='Nombre en hebreo (opcional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario asociado si el paciente tiene cuenta de login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistholisticconfig',
            name='weights',
            field=models.JSONField(default=dict, help_text='Pesos por disciplina: {"kabbalah_numerology": 0.20, "tarot_evolutivo": 0.20, "astrologia_terapeutica": 0.20, "transgeneracional": 0.20, "biodecodificacion": 0.20}'),
        ),
    ]
