# Generated by Django 5.2.9 on 2026-01-24 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_alter_resonanciarelation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioEmotionalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('emotional_state', models.CharField(choices=[('better', 'Mejor'), ('same', 'Igual'), ('worse', 'Peor'), ('unknown', 'Sin evaluar')], default='unknown', max_length=16)),
                ('observations_count', models.PositiveIntegerField(default=0)),
                ('hypotheses_count', models.PositiveIntegerField(default=0)),
                ('synthesis_completed', models.BooleanField(default=False)),
                ('regions_observed', models.JSONField(blank=True, default=list, help_text='Lista de IDs de regiones corporales observadas')),
                ('heatmap_data', models.JSONField(blank=True, default=dict, help_text='Datos de intensidad por región: {region_id: intensity 0-10}')),
                ('patient_notes', models.TextField(blank=True, help_text='Notas del consultante sobre síntomas y sensaciones')),
                ('patient_feeling_score', models.PositiveSmallIntegerField(blank=True, help_text='Puntuación de cómo se siente el consultante (1-10)', null=True)),
                ('patient_discomfort_regions', models.JSONField(blank=True, default=list, help_text='Regiones donde el consultante reporta molestias')),
                ('is_closed', models.BooleanField(default=False, help_text='Indica si la sesión ha sido cerrada')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_emotional_sessions', to='api.patient')),
                ('therapist', models.ForeignKey(blank=True, help_text='Terapeuta asignado a la sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_emotional_sessions_as_therapist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión BioEmotional',
                'verbose_name_plural': 'Sesiones BioEmotionales',
                'ordering': ['patient', '-date'],
                'indexes': [models.Index(fields=['patient', 'date'], name='api_bioemot_patient_fd11d1_idx'), models.Index(fields=['patient', 'is_closed'], name='api_bioemot_patient_970efd_idx'), models.Index(fields=['therapist', 'date'], name='api_bioemot_therapi_c593c3_idx')],
            },
        ),
    ]
