# Generated by Django 5.2.9 on 2026-01-25 23:08

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_add_bioemotional_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyAIInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation_type', models.CharField(choices=[('natal', 'Carta Natal'), ('transits', 'Tránsitos'), ('progressions', 'Progresiones'), ('solar_return', 'Retorno Solar'), ('situation', 'Situación Actual')], help_text='Type of astrological interpretation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this interpretation was generated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this interpretation was updated')),
                ('interpretation_text', models.TextField(help_text='AI-generated interpretation content')),
                ('input_context', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Input data used to generate interpretation (chart data, dates, etc.)', null=True)),
                ('model_version', models.CharField(default='gemini-2.5-flash', help_text='AI model version used', max_length=50)),
                ('token_count', models.IntegerField(blank=True, help_text='Approximate token count of interpretation', null=True)),
                ('is_shared_with_patient', models.BooleanField(default=False, help_text='Whether this interpretation is shared with the patient')),
                ('shared_at', models.DateTimeField(blank=True, help_text='When this interpretation was shared with patient', null=True)),
                ('therapist_notes', models.TextField(blank=True, default='', help_text='Private notes from therapist about this interpretation')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this interpretation is archived')),
                ('created_by', models.ForeignKey(help_text='Therapist who generated this interpretation', on_delete=django.db.models.deletion.CASCADE, related_name='ai_interpretations_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient for whom this interpretation was generated', on_delete=django.db.models.deletion.CASCADE, related_name='ai_interpretations', to='api.patient')),
            ],
            options={
                'verbose_name': 'AI Interpretation',
                'verbose_name_plural': 'AI Interpretations',
                'db_table': 'astrology_ai_interpretation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AstrologyAIInterpretationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Version number (1, 2, 3...)')),
                ('interpretation_text', models.TextField(help_text='Interpretation content for this version')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
                ('created_by', models.ForeignKey(help_text='Who created this version', on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_versions_created', to=settings.AUTH_USER_MODEL)),
                ('interpretation', models.ForeignKey(help_text='Parent interpretation', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.astrologyaiinterpretation')),
            ],
            options={
                'verbose_name': 'AI Interpretation Version',
                'verbose_name_plural': 'AI Interpretation Versions',
                'db_table': 'astrology_ai_interpretation_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='astrologyaiinterpretation',
            index=models.Index(fields=['patient', 'interpretation_type', '-created_at'], name='astrology_a_patient_1efacf_idx'),
        ),
        migrations.AddIndex(
            model_name='astrologyaiinterpretation',
            index=models.Index(fields=['created_by', '-created_at'], name='astrology_a_created_d2fed5_idx'),
        ),
        migrations.AddIndex(
            model_name='astrologyaiinterpretation',
            index=models.Index(fields=['is_shared_with_patient'], name='astrology_a_is_shar_71cf8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='astrologyaiinterpretationversion',
            unique_together={('interpretation', 'version_number')},
        ),
    ]
