# Generated by Django 5.2.9 on 2026-01-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_add_astrology_ai_interpretation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologyaiinterpretation',
            name='interpretation_type',
            field=models.CharField(choices=[('natal', 'Carta Natal'), ('transits', 'Tránsitos'), ('progressions', 'Progresiones'), ('solar_return', 'Retorno Solar'), ('situation', 'Situación Actual'), ('psychological_archetypes', 'Psico: Arquetipos'), ('psychological_shadow', 'Psico: Sombra'), ('psychological_individuation', 'Psico: Individuación'), ('psychological_sins', 'Psico: Arquetipos Pecados')], help_text='Type of astrological interpretation', max_length=30),
        ),
    ]
