# Generated by Django 5.2.9 on 2026-01-31 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_extend_interpretation_type_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultante',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único global del consultante', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Nombre completo del consultante', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('birth_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('birth_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('biological_sex', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('intersex', 'Intersexual'), ('unknown', 'Desconocido'), ('not_recorded', 'Sin registro')], default='unknown', max_length=20)),
                ('gender_identity', models.CharField(blank=True, choices=[('woman', 'Mujer'), ('man', 'Hombre'), ('non_binary', 'No binaria'), ('other', 'Otra'), ('prefer_not_to_say', 'Prefiere no decirlo'), ('not_recorded', 'Sin registro')], default='not_recorded', max_length=20)),
                ('therapy_status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('archived', 'Archivado')], default='active', max_length=20)),
                ('pause_reason', models.TextField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('consent_federation', models.BooleanField(default=False, help_text='Consiente compartir datos en Federation Hub (SCDF, SCID-5, MSHE)')),
                ('consent_federation_date', models.DateTimeField(blank=True, null=True)),
                ('main_complaint', models.TextField(blank=True, help_text='Motivo principal de consulta', null=True)),
                ('clinical_history', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('therapy_level', models.CharField(choices=[('exploratory', 'Exploratorio'), ('therapeutic', 'Terapéutico'), ('transformational', 'Transformacional'), ('mastery', 'Maestría')], default='exploratory', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='consultante_avatars/')),
                ('legacy_patient_id', models.IntegerField(blank=True, help_text='ID del Patient legacy para migración', null=True, unique=True)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultante_status_changes', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(help_text='Terapeuta asignado a este consultante', on_delete=django.db.models.deletion.CASCADE, related_name='consultantes', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.OneToOneField(help_text='Cuenta de usuario para login y asignaciones de tests', on_delete=django.db.models.deletion.CASCADE, related_name='consultante_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultante',
                'verbose_name_plural': 'Consultantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
