# Generated by Django 5.2.9 on 2026-01-31 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_consultante_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultante_id', models.IntegerField(blank=True, help_text='ID del consultante (si aplica)', null=True)),
                ('operation', models.CharField(choices=[('text_extraction', 'Text Extraction'), ('concept_analysis', 'Concept Analysis'), ('meditation_generation', 'Meditation Generation'), ('reflection_questions', 'Reflection Questions'), ('text_summary', 'Text Summary'), ('symbolic_correlation', 'Symbolic Correlation')], max_length=50)),
                ('prompt_hash', models.CharField(help_text='SHA-256 hash of the prompt (privacy-preserving)', max_length=64)),
                ('prompt_length', models.IntegerField(help_text='Length of the original prompt')),
                ('response_length', models.IntegerField(help_text='Length of the AI response')),
                ('validation_passed', models.BooleanField(default=True, help_text='Whether prompt validation passed')),
                ('violations_found', models.JSONField(blank=True, default=list, help_text='List of validation violations (if any)')),
                ('therapist_approved', models.BooleanField(default=False, help_text='Whether therapist approved the output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabala_ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log (Cábala)',
                'verbose_name_plural': 'AI Usage Logs (Cábala)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'created_at'], name='api_aiusage_therapi_e026b7_idx'), models.Index(fields=['operation', 'created_at'], name='api_aiusage_operati_87df54_idx'), models.Index(fields=['consultante_id'], name='api_aiusage_consult_524060_idx')],
            },
        ),
    ]
