# Generated by Django 5.2.9 on 2026-06-05 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_therapist_patient_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('kabbalah', 'Kabbalah'), ('bioemotion', 'Bioemotion'), ('tarot', 'Tarot'), ('clinical', 'Clinical'), ('astrology', 'Astrology')], db_index=True, max_length=32)),
                ('lane', models.CharField(choices=[('symbolic', 'Symbolic'), ('clinical_support', 'Clinical Support')], db_index=True, max_length=32)),
                ('source_type', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.CharField(db_index=True, max_length=96)),
                ('structured', models.JSONField(blank=True, default=dict)),
                ('text_summary', models.TextField()),
                ('consent_scope', models.CharField(choices=[('store_with_consent', 'Store with consent'), ('store_anonymized', 'Store anonymized'), ('no_store', 'No store')], default='store_with_consent', max_length=32)),
                ('base_weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_snapshots', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot de proceso PIP',
                'verbose_name_plural': 'Snapshots de proceso PIP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lane', models.CharField(choices=[('symbolic', 'Symbolic'), ('clinical_support', 'Clinical Support')], db_index=True, max_length=32)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to='api.processsnapshot')),
            ],
            options={
                'verbose_name': 'Chunk de embedding PIP',
                'verbose_name_plural': 'Chunks de embedding PIP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=96)),
                ('lane', models.CharField(choices=[('symbolic', 'Symbolic'), ('clinical_support', 'Clinical Support')], max_length=32)),
                ('source_type', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.CharField(db_index=True, max_length=96)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_events', to='api.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de proceso PIP',
                'verbose_name_plural': 'Eventos de proceso PIP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'patient', '-created_at'], name='api_process_therapi_b9427c_idx'), models.Index(fields=['event_type', '-created_at'], name='api_process_event_t_506099_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='processsnapshot',
            index=models.Index(fields=['therapist', 'patient', 'lane', '-created_at'], name='api_process_therapi_510176_idx'),
        ),
        migrations.AddIndex(
            model_name='processsnapshot',
            index=models.Index(fields=['domain', 'lane', '-created_at'], name='api_process_domain_f90ebb_idx'),
        ),
        migrations.AddConstraint(
            model_name='processsnapshot',
            constraint=models.UniqueConstraint(fields=('therapist', 'source_type', 'source_id'), name='api_process_snapshot_source_unique'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['therapist', 'patient', 'lane', '-created_at'], name='api_embeddi_therapi_486bd8_idx'),
        ),
    ]
