# Generated by Django 5.2.9 on 2026-01-31 23:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_cabala_ai_usage_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrativeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('soul_letter', 'Carta del Alma'), ('journey_map', 'Mapa del Viaje'), ('process_book', 'Libro del Proceso')], help_text='Tipo de documento narrativo', max_length=20)),
                ('title', models.CharField(help_text='Título del documento', max_length=255)),
                ('content', models.JSONField(help_text='Contenido del documento en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_consultante', models.BooleanField(default=True, help_text='Si el consultante puede ver este documento')),
                ('consultante', models.ForeignKey(help_text='Consultante dueño del documento', on_delete=django.db.models.deletion.CASCADE, related_name='narrative_documents', to='api.consultante')),
                ('generated_by', models.ForeignKey(blank=True, help_text='Terapeuta que generó el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_narratives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Narrativo',
                'verbose_name_plural': 'Documentos Narrativos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultante', '-created_at'], name='api_narrati_consult_15711f_idx'), models.Index(fields=['document_type', '-created_at'], name='api_narrati_documen_27dd36_idx')],
            },
        ),
    ]
