# Generated by Django 6.0.6 on 2026-06-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_symbolicsessionnote'),
        ('api', '0094_astrologysessionreport'),
    ]

    operations = [
    ]
