# Generated by Django 6.0.6 on 2026-06-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_merge_20260610_1731'),
    ]

    operations = []
