# Generated by Django 6.0.6 on 2026-06-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_merge_20260610_1731'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='astrologysessionreport',
            new_name='astrology_s_patient_bdb3b5_idx',
            old_name='astro_report_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='astrologysessionreport',
            new_name='astrology_s_is_shar_ec2e86_idx',
            old_name='astro_report_shared_idx',
        ),
    ]
