# Generated by Django 6.0.6 on 2026-06-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_clinical_onboarding'),
        ('api', '0096_rename_astro_report_patient_idx_astrology_s_patient_bdb3b5_idx_and_more'),
    ]

    operations = [
    ]
