# Generated by Django 6.0.6 on 2026-06-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_ai_usage_event'),
        ('api', '0097_merge_20260610_1749'),
    ]

    operations = [
    ]
