# Generated by Django 6.0.6 on 2026-06-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_merge_0096_ai_usage_event_0097_merge_20260610_1749'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusageevent',
            new_name='ai_usage_ev_therapi_eb5acf_idx',
            old_name='ai_usage_th_period_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusageevent',
            new_name='ai_usage_ev_task_ty_f91e24_idx',
            old_name='ai_usage_task_created_idx',
        ),
    ]
