# Generated by Django 6.0.6 on 2026-06-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_rename_ai_usage_th_period_idx_ai_usage_ev_therapi_eb5acf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='send_credentials_via',
            field=models.JSONField(blank=True, default=list, help_text='Canales para enviar credenciales, p.ej. ["email", "telegram"]'),
        ),
        migrations.AddField(
            model_name='patient',
            name='telegram',
            field=models.CharField(blank=True, default='', help_text='Usuario de Telegram sin @ (handle)', max_length=64),
        ),
    ]
