# Generated by Django 6.0.6 on 2026-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_patient_telegram_send_credentials_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Chat ID de Telegram vinculado vía bot (notificaciones)', null=True),
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('purpose', models.CharField(choices=[('patient_welcome', 'Bienvenida consultante'), ('user_link', 'Vincular cuenta existente'), ('invitation', 'Invitación terapeuta')], max_length=32)),
                ('user_id', models.IntegerField(help_text='Usuario Django a vincular')),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('invitation_id', models.IntegerField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token enlace Telegram',
                'verbose_name_plural': 'Tokens enlace Telegram',
                'indexes': [models.Index(fields=['code', 'expires_at'], name='tg_link_code_exp_idx')],
            },
        ),
    ]
