# Generated by Django 6.0.6 on 2026-06-12 14:40
# Idempotente: prod ya tenía 0100_telegram_notifications (stash) aplicada ayer.

from django.db import migrations, models


def _table_exists(schema_editor, table: str) -> bool:
    # Introspección de Django: funciona en PostgreSQL (prod) y SQLite (tests).
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return table in connection.introspection.table_names(cursor)


def _column_exists(schema_editor, table: str, column: str) -> bool:
    if not _table_exists(schema_editor, table):
        return False
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table)
    return any(col.name == column for col in description)


def apply_telegram_schema(apps, schema_editor):
    if not _column_exists(schema_editor, 'api_userprofile', 'telegram_chat_id'):
        schema_editor.execute(
            'ALTER TABLE api_userprofile ADD COLUMN telegram_chat_id BIGINT NULL'
        )

    if not _table_exists(schema_editor, 'api_telegramlinktoken'):
        # Dentro de SeparateDatabaseAndState el estado histórico aún no contiene
        # el modelo (CreateModel va en state_operations), así que usamos el
        # modelo concreto. La migración es contemporánea al modelo.
        from api.models import TelegramLinkToken
        schema_editor.create_model(TelegramLinkToken)


def reverse_telegram_schema(apps, schema_editor):
    if _table_exists(schema_editor, 'api_telegramlinktoken'):
        from api.models import TelegramLinkToken
        schema_editor.delete_model(TelegramLinkToken)

    if _column_exists(schema_editor, 'api_userprofile', 'telegram_chat_id'):
        schema_editor.execute(
            'ALTER TABLE api_userprofile DROP COLUMN telegram_chat_id'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_patient_telegram_send_credentials_via'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='telegram_chat_id',
                    field=models.BigIntegerField(
                        blank=True,
                        help_text='Chat ID de Telegram vinculado vía bot (notificaciones)',
                        null=True,
                    ),
                ),
                migrations.CreateModel(
                    name='TelegramLinkToken',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                        ('purpose', models.CharField(choices=[('patient_welcome', 'Bienvenida consultante'), ('user_link', 'Vincular cuenta existente'), ('invitation', 'Invitación terapeuta')], max_length=32)),
                        ('user_id', models.IntegerField(help_text='Usuario Django a vincular')),
                        ('patient_id', models.IntegerField(blank=True, null=True)),
                        ('invitation_id', models.IntegerField(blank=True, null=True)),
                        ('context', models.JSONField(blank=True, default=dict)),
                        ('expires_at', models.DateTimeField()),
                        ('consumed_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Token enlace Telegram',
                        'verbose_name_plural': 'Tokens enlace Telegram',
                        'indexes': [models.Index(fields=['code', 'expires_at'], name='tg_link_code_exp_idx')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(apply_telegram_schema, reverse_telegram_schema),
            ],
        ),
    ]
