# Generated by Django 6.0.6 on 2026-06-12 14:40
# Idempotente: prod ya tenía 0100_telegram_notifications (stash) aplicada ayer.

from django.db import migrations, models


def _column_exists(schema_editor, table: str, column: str) -> bool:
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table})")
            return any(row[1] == column for row in cursor.fetchall())
        cursor.execute(
            "SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = %s",
            [table, column],
        )
        return cursor.fetchone() is not None


def _table_exists(schema_editor, table: str) -> bool:
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'sqlite':
            cursor.execute(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name=%s",
                [table],
            )
            return cursor.fetchone() is not None
        cursor.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = %s",
            [table],
        )
        return cursor.fetchone() is not None


def apply_telegram_schema(apps, schema_editor):
    if not _column_exists(schema_editor, 'api_userprofile', 'telegram_chat_id'):
        if schema_editor.connection.vendor == 'sqlite':
            schema_editor.execute(
                'ALTER TABLE api_userprofile ADD COLUMN telegram_chat_id INTEGER NULL'
            )
        else:
            schema_editor.execute(
                'ALTER TABLE api_userprofile ADD COLUMN telegram_chat_id BIGINT NULL'
            )

    if not _table_exists(schema_editor, 'api_telegramlinktoken'):
        if schema_editor.connection.vendor != 'sqlite':
            TelegramLinkToken = apps.get_model('api', 'TelegramLinkToken')
            schema_editor.create_model(TelegramLinkToken)


def reverse_telegram_schema(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        return

    if _table_exists(schema_editor, 'api_telegramlinktoken'):
        TelegramLinkToken = apps.get_model('api', 'TelegramLinkToken')
        schema_editor.delete_model(TelegramLinkToken)

    if _column_exists(schema_editor, 'api_userprofile', 'telegram_chat_id'):
        schema_editor.execute(
            'ALTER TABLE api_userprofile DROP COLUMN telegram_chat_id'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_patient_telegram_send_credentials_via'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='telegram_chat_id',
                    field=models.BigIntegerField(
                        blank=True,
                        help_text='Chat ID de Telegram vinculado vía bot (notificaciones)',
                        null=True,
                    ),
                ),
                migrations.CreateModel(
                    name='TelegramLinkToken',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                        ('purpose', models.CharField(choices=[('patient_welcome', 'Bienvenida consultante'), ('user_link', 'Vincular cuenta existente'), ('invitation', 'Invitación terapeuta')], max_length=32)),
                        ('user_id', models.IntegerField(help_text='Usuario Django a vincular')),
                        ('patient_id', models.IntegerField(blank=True, null=True)),
                        ('invitation_id', models.IntegerField(blank=True, null=True)),
                        ('context', models.JSONField(blank=True, default=dict)),
                        ('expires_at', models.DateTimeField()),
                        ('consumed_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Token enlace Telegram',
                        'verbose_name_plural': 'Tokens enlace Telegram',
                        'indexes': [models.Index(fields=['code', 'expires_at'], name='tg_link_code_exp_idx')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(apply_telegram_schema, reverse_telegram_schema),
            ],
        ),
    ]