# Generated by Django 6.0.6 on 2026-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_telegram_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrecord',
            name='kind',
            field=models.CharField(choices=[('clinical_test', 'Clinical Test'), ('kabbalah', 'Kabbalah'), ('astrology', 'Astrology'), ('tarot', 'Tarot'), ('transgenerational', 'Transgenerational'), ('biodecoding', 'Biodecoding (BioEmotional)'), ('legacy', 'Legacy'), ('holistic_evaluative_synthesis', 'Holistic Evaluative Synthesis')], help_text='Tipo de análisis ejecutado.', max_length=32),
        ),
    ]
