# Generated by Django 6.0.6 on 2026-06-13 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_update_past_lives_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResonanceClientCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Captura cliente (Resonancia)',
                'verbose_name_plural': 'Capturas cliente (Resonancia)',
            },
        ),
        migrations.AddField(
            model_name='genealogyperson',
            name='birth_order_number',
            field=models.IntegerField(blank=True, help_text='Número de orden de nacimiento (cuenta abortos/fallecidos). 1-N.', null=True),
        ),
        migrations.AddField(
            model_name='genealogyperson',
            name='is_abortion',
            field=models.BooleanField(default=False, help_text='Aborto o bebé fallecido. Ocupa su posición numérica en el sistema.'),
        ),
        migrations.AddField(
            model_name='genealogyperson',
            name='is_deceased',
            field=models.BooleanField(default=False, help_text='Persona fallecida.'),
        ),
        migrations.AddField(
            model_name='genealogyperson',
            name='side',
            field=models.CharField(blank=True, choices=[('paterno', 'Paterno'), ('materno', 'Materno')], help_text='Rama paterna o materna (solo aplica a generaciones -1/-2).', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='resonanciarelation',
            name='direction',
            field=models.CharField(choices=[('a_to_b', 'a → b'), ('bidireccional', 'Bidireccional')], default='bidireccional', max_length=16),
        ),
        migrations.AddField(
            model_name='resonanciarelation',
            name='person_a',
            field=models.ForeignKey(blank=True, help_text='Persona A (origen de la resonancia).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resonances_as_a', to='api.genealogyperson'),
        ),
        migrations.AddField(
            model_name='resonanciarelation',
            name='person_b',
            field=models.ForeignKey(blank=True, help_text='Persona B (destino/eco de la resonancia).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resonances_as_b', to='api.genealogyperson'),
        ),
        migrations.AddField(
            model_name='resonanciarelation',
            name='relevance',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=8),
        ),
        migrations.AddField(
            model_name='resonanciarelation',
            name='resonance_type',
            field=models.CharField(blank=True, choices=[('resonancia_por_numero', 'Resonancia por Número'), ('complejo_tio', 'Complejo del Tío'), ('duplica_generacional', 'Duplica Generacional'), ('repeticion_nombre', 'Repetición de Nombre'), ('sindrome_aniversario', 'Síndrome de Aniversario'), ('hueco_aborto', 'Hueco por Aborto/Fallecido'), ('proyecto_objetivo', 'Proyecto/Objetivo No Logrado'), ('mismo_rol_sistema', 'Mismo Rol en el Sistema'), ('exclusion', 'Exclusión (Hellinger)'), ('lealtad_invisible', 'Lealtad Invisible (Hellinger)'), ('asunto_de_orden', 'Asunto de Orden (Hellinger)')], help_text='Tipo de resonancia (Armoni/Hellinger). Null en registros legacy.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='resonanciarelation',
            name='source',
            field=models.CharField(choices=[('terapeuta', 'Terapeuta'), ('cliente', 'Cliente')], default='terapeuta', max_length=16),
        ),
        migrations.AddField(
            model_name='resonanciarelation',
            name='source_ref',
            field=models.CharField(blank=True, help_text='Referencia libre a la fuente (sesión, nota, test).', max_length=255),
        ),
        migrations.AddField(
            model_name='resonanciarelation',
            name='suggested_rectification',
            field=models.CharField(blank=True, choices=[('nombre', 'Nombre'), ('accion', 'Acción'), ('lugar', 'Lugar')], max_length=16, null=True),
        ),
        migrations.AddIndex(
            model_name='resonanciarelation',
            index=models.Index(fields=['subject', '-created_at'], name='resrel_subj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resonanciarelation',
            index=models.Index(fields=['subject', 'resonance_type'], name='resrel_subj_type_idx'),
        ),
        migrations.AddField(
            model_name='resonanceclientcapture',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonance_captures', to='api.patient'),
        ),
        migrations.AddField(
            model_name='resonanceclientcapture',
            name='therapist',
            field=models.ForeignKey(limit_choices_to={'profile__user_type': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='resonance_captures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resonanceclientcapture',
            unique_together={('therapist', 'patient')},
        ),
    ]
