# Generated by Django 5.2.9 on 2026-06-13
# Renumbered 0106 → 0107: prod already applied 0106_resonance_map_backbone (deploy rsync).

from django.db import migrations


OLD_NAME = "SWM MCMI-4 SIGNAL"
NEW_NAME = "Señal de la Matriz Cósmica"
NEW_DESCRIPTION = (
    "Evaluación general breve para abrir tu recorrido de exploración personal. "
    "Te ayudará a iniciar la reflexión y las siguientes etapas con tu terapeuta."
)


def forwards(apps, schema_editor):
    TestModule = apps.get_model("api", "TestModule")
    TestModule.objects.filter(code="mcmi4-signal").update(
        name=NEW_NAME,
        public_name=NEW_NAME,
        description=NEW_DESCRIPTION,
    )


def backwards(apps, schema_editor):
    TestModule = apps.get_model("api", "TestModule")
    TestModule.objects.filter(code="mcmi4-signal").update(
        name=OLD_NAME,
        public_name=OLD_NAME,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0106_resonance_map_backbone"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]