# Generated by Django 5.2.9 on 2026-01-23 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Unique code identifier (e.g., 'TAROT_EVOLUTIVO')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this workspace type')),
                ('version', models.CharField(default='1.0.0', help_text='Semantic version', max_length=20)),
                ('config_schema', models.JSONField(default=dict, help_text='JSON Schema for workspace configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workspace type is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace Definition',
                'verbose_name_plural': 'Workspace Definitions',
                'db_table': 'swm_tarot_workspace_definition',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spread_type', models.CharField(choices=[('free', 'Tirada Libre'), ('tree_of_life', 'Árbol de la Vida'), ('cross', 'Cruz Celta'), ('three_cards', 'Tres Cartas (PPF)'), ('horseshoe', 'Herradura'), ('sephiroth_path', 'Sendero Sefirótico')], default='free', help_text='Type of Tarot spread', max_length=30)),
                ('tarot_system', models.CharField(choices=[('rider-waite', 'Rider-Waite-Smith'), ('thoth', 'Thoth (Crowley)'), ('marseille', 'Marsella'), ('golden-dawn', 'Golden Dawn'), ('bota', 'B.O.T.A.')], default='rider-waite', help_text='Tarot deck system used', max_length=30)),
                ('total_cards', models.PositiveIntegerField(default=0, help_text='Total cards in the spread (0 = variable)')),
                ('has_reversed', models.BooleanField(default=True, help_text='Whether reversed cards are used')),
                ('status', models.CharField(choices=[('created', 'Creado'), ('in_progress', 'En Progreso'), ('sealed', 'Sellado'), ('reviewed', 'Revisado'), ('archived', 'Archivado'), ('cancelled', 'Cancelado')], default='created', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Instance-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When work actually began', null=True)),
                ('sealed_at', models.DateTimeField(blank=True, help_text='When the workspace was sealed', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the workspace was reviewed', null=True)),
                ('creator_user', models.ForeignKey(help_text='The therapist who created this workspace', on_delete=django.db.models.deletion.PROTECT, related_name='tarot_workspaces_created', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='swm_tarot.workspacedefinition')),
                ('subject_user', models.ForeignKey(help_text='The patient this workspace belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='tarot_workspaces_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Instance',
                'verbose_name_plural': 'Workspace Instances',
                'db_table': 'swm_tarot_workspace_instance',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text="Action identifier (e.g., 'spread_saved')", max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='tarot_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='swm_tarot.workspaceinstance')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'db_table': 'swm_tarot_workspace_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkspacePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('executor', 'Ejecutor'), ('observer', 'Observador'), ('reviewer', 'Revisor'), ('admin', 'Administrador')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarot_permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='swm_tarot.workspaceinstance')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarot_permissions_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarot_workspace_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Permission',
                'verbose_name_plural': 'Workspace Permissions',
                'db_table': 'swm_tarot_workspace_permission',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('setup', 'Configuración'), ('selection', 'Selección de Cartas'), ('exploration', 'Exploración Simbólica'), ('synthesis', 'Síntesis'), ('closing', 'Cierre')], default='setup', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('progress_data', models.JSONField(default=dict, help_text='Session progress and state data')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='swm_tarot.workspaceinstance')),
                ('user', models.ForeignKey(help_text='User who initiated this session', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Session',
                'verbose_name_plural': 'Workspace Sessions',
                'db_table': 'swm_tarot_workspace_session',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('spread', 'Tirada'), ('therapist_notes', 'Notas del Terapeuta'), ('symbolic_map', 'Mapa Simbólico'), ('session_summary', 'Resumen de Sesión')], max_length=30)),
                ('content', models.JSONField(help_text='Artifact content as JSON')),
                ('is_sealed', models.BooleanField(default=False, help_text='Sealed artifacts cannot be modified')),
                ('version', models.PositiveIntegerField(default=1, help_text='Artifact version (increments on update)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarot_artifacts_created', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='swm_tarot.workspaceinstance')),
                ('session', models.ForeignKey(blank=True, help_text='Session that created this artifact (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='swm_tarot.workspacesession')),
            ],
            options={
                'verbose_name': 'Workspace Artifact',
                'verbose_name_plural': 'Workspace Artifacts',
                'db_table': 'swm_tarot_workspace_artifact',
            },
        ),
        migrations.AddIndex(
            model_name='workspaceinstance',
            index=models.Index(fields=['subject_user', 'status'], name='swm_tarot_w_subject_37339f_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinstance',
            index=models.Index(fields=['creator_user', 'status'], name='swm_tarot_w_creator_fec06c_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinstance',
            index=models.Index(fields=['status', 'created_at'], name='swm_tarot_w_status_41d825_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['instance', 'timestamp'], name='swm_tarot_w_instanc_9ff930_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='swm_tarot_w_user_id_74e45a_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='swm_tarot_w_action_57dc4b_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacepermission',
            index=models.Index(fields=['user', 'is_active'], name='swm_tarot_w_user_id_5ba665_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacepermission',
            unique_together={('instance', 'user', 'level')},
        ),
        migrations.AddIndex(
            model_name='workspacesession',
            index=models.Index(fields=['instance', 'is_active'], name='swm_tarot_w_instanc_f8cb5d_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceartifact',
            index=models.Index(fields=['instance', 'artifact_type'], name='swm_tarot_w_instanc_2601ab_idx'),
        ),
    ]
