export const SCALE_LABELS: Record<number, string> = {
  0: 'Siempre',
  1: 'Casi siempre',
  2: 'Muchas veces',
  3: 'A veces',
  4: 'Pocas veces',
  5: 'Nunca',
};

export const eat26SpiritDefinition = {
  code: 'eat26_spirit',
  name: 'EAT-26-Spirit — Eternal Abundance Threshold',
  purpose: 'Exploración simbólica de Malkhut y la relación con la abundancia corporal',
  estimated_time_minutes: 10,
  disclaimer: 'Exploración simbólica no clínica. No sustituye diagnóstico médico.',
  scale: SCALE_LABELS,
  questions: [
    { id: 'q1',  text: 'Me aterra la idea de engordar.' },
    { id: 'q2',  text: 'Evito comer cuando tengo hambre.' },
    { id: 'q3',  text: 'Me preocupa y obsesiona el tema de la comida.' },
    { id: 'q4',  text: 'Me he dado atracones de comida sintiéndome incapaz de parar.' },
    { id: 'q5',  text: 'Corto mis alimentos en trozos pequeños.' },
    { id: 'q6',  text: 'Conozco el valor calórico de los alimentos que ingiero.' },
    { id: 'q7',  text: 'Evito especialmente alimentos con muchos carbohidratos (pan, arroz, patatas).' },
    { id: 'q8',  text: 'Siento que los demás prefieren que yo coma más.' },
    { id: 'q9',  text: 'Vomito después de comer.' },
    { id: 'q10', text: 'Me siento muy culpable después de comer.' },
    { id: 'q11', text: 'Me obsesiona el deseo de estar más delgado/a.' },
    { id: 'q12', text: 'Pienso en quemar calorías cuando hago ejercicio.' },
    { id: 'q13', text: 'Los demás piensan que estoy demasiado delgado/a.' },
    { id: 'q14', text: 'Me preocupa la idea de tener grasa en el cuerpo.' },
    { id: 'q15', text: 'Tardo más en comer que los demás.' },
    { id: 'q16', text: 'Evito los alimentos que contienen azúcar.' },
    { id: 'q17', text: 'Como alimentos de dieta.' },
    { id: 'q18', text: 'Siento que la comida controla mi vida.' },
    { id: 'q19', text: 'Muestro autocontrol ante la comida.' },
    { id: 'q20', text: 'Siento que los demás me presionan para que coma.' },
    { id: 'q21', text: 'Paso demasiado tiempo pensando en la comida.' },
    { id: 'q22', text: 'Me siento incómodo/a después de comer dulces.' },
    { id: 'q23', text: 'Me comprometo con comportamientos de dieta estricta.' },
    { id: 'q24', text: 'Me gusta sentir el estómago vacío.' },
    { id: 'q25', text: 'Disfruto probando nuevos alimentos sabrosos.' },
    { id: 'q26', text: 'Siento el impulso de vomitar después de las comidas.' },
  ],
};
