"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.x.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure--$p6@)i9!h64-xy0vc9x!5ufj)vob_&ct3ll6)8%jdssz2df&@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,testserver',
    cast=lambda v: [s.strip() for s in v.split(',')],
)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Apps de Terceros ---
    'rest_framework',   # Para crear la API
    'corsheaders',      # Para permitir conexión con Next.js
    'rest_framework.authtoken',  # <--- ¡AGREGA ESTA LÍNEA! 🆕
    
    # --- Mis Apps ---
    'api',              # Tu app de lógica cabalística
    'astrology',        # Módulo de astrología (cálculos astronómicos)
    'courses',          # Sistema LMS de cursos
    # The `symbolic` package is not a Python package in this repo (it's JS/TS).
    # Comment out invalid references so Django can start locally.
    # 'symbolic.72_angels',  # SWM 72 Ángeles Engine
    # 'symbolic.swm_v3',  # SWM v3 governed symbolic readings (Phase 3)
]

MIDDLEWARE = [
    # CORS debe ir lo más arriba posible, antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware', 
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración CORS ---
# Permite que el frontend (Next.js) haga peticiones a este backend
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    # En producción, este valor debe ser provisto por env var.
    # Incluimos defaults seguros para desarrollo y previews de Vercel.
    default='http://localhost:3000,http://localhost:3001,https://*.vercel.app',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# Para deployments de preview en Vercel, es común que el dominio cambie.
# Esta regex permite `https://<cualquier-subdominio>.vercel.app`.
# Nota: si usas CORS_ALLOW_CREDENTIALS=True, no puedes usar "*"; la regex es la opción correcta.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://.*\.vercel\.app$',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF - Permitir peticiones del frontend
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    # En producción, este valor debe ser provisto por env var.
    # Agregamos wildcard para Vercel previews.
    default='http://localhost:3000,http://localhost:3001,https://*.vercel.app',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# Email Configuration
# Para desarrollo, usar console backend (muestra emails en la consola)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Para producción, descomentar y configurar:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # o tu servidor SMTP
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu-contraseña-o-app-password'
DEFAULT_FROM_EMAIL = 'Tony Blanco <noreply@tonyblanco.com>'
EMAIL_SUBJECT_PREFIX = '[Kabbalah] '

# Frontend URL (for password reset links, etc.)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Gemini AI Configuration
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-1.5-flash')

# Astrology Kerykeion - AI snippets (therapist in-session guidance)
# When enabled, the backend may generate short AI-written (non-verbatim) summaries
# for curated Sefaria references.
KERYKEION_AI_SNIPPETS_ENABLED = config('KERYKEION_AI_SNIPPETS_ENABLED', default=False, cast=bool)
ASTRO_MULTITECH_ENABLED = config('ASTRO_MULTITECH_ENABLED', default=True, cast=bool)
KERYKEION_AI_SNIPPETS_MODEL = config('KERYKEION_AI_SNIPPETS_MODEL', default='')
