"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.x.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure--$p6@)i9!h64-xy0vc9x!5ufj)vob_&ct3ll6)8%jdssz2df&@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,testserver',
    cast=lambda v: [s.strip() for s in v.split(',')],
)

# Detrás de Cloudflare / nginx (HTTPS terminado en el edge)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Apps de Terceros ---
    'rest_framework',   # Para crear la API
    'corsheaders',      # Para permitir conexión con Next.js
    'rest_framework.authtoken',  # <--- ¡AGREGA ESTA LÍNEA! 🆕
    
    # --- Mis Apps ---
    'api',              # Tu app de lógica cabalística
    'astrology',        # Módulo de astrología (cálculos astronómicos)
    'courses',          # Sistema LMS de cursos
    'swm.mcmi4',        # MCMI-4 Místico SWM (Specialized Workspace Module)
    'swm.mcmi4_reflection',  # MCMI-4 Reflection SWM (Experiential reflection)
    'swm.tarot',        # SWM Tarot Evolutivo (Symbolic Tarot Workspace)
    'swm.cabala',       # SWM Cábala Aplicada (Tree of Life Workspace)
    'swm.transgenerational',  # SWM Transgeneracional Profundo (Psychogenealogy Workspace)
    'swm.sha',          # SWM Auditoría de Armonía Sefirótica (SHA)
    'api.inquiry',            # Active Inquiry Engine (Patient context collection)
    # Symbolic systems (Python implementations)
    'symbolic.swm_v3',  # SWM v3 governed symbolic readings (Phase 3)
]

MIDDLEWARE = [
    # CORS debe ir lo más arriba posible, antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware', 
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

_database_url = os.environ.get('DATABASE_URL') or config('DATABASE_URL', default='')
if _database_url:
    _db = urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (_db.path or '/').lstrip('/'),
            'USER': _db.username,
            'PASSWORD': _db.password,
            'HOST': _db.hostname,
            'PORT': str(_db.port or 5432),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración CORS ---
# Permite que el frontend (Next.js) haga peticiones a este backend
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    # Producción: studios33.app vía env en Hetzner. Solo localhost en dev por defecto.
    default='http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

CORS_ALLOWED_ORIGIN_REGEXES: list[str] = []
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF - Permitir peticiones del frontend
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# Email Configuration
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
if EMAIL_HOST and EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Studios33 <noreply@studios33.app>')
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX', default='[Studios33] ')

# Frontend URL (for password reset links, etc.)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Gemini AI Configuration
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-1.5-flash')

# OpenAI Configuration (GPT-4o-mini for fallback)
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
OPENAI_MODEL = config('OPENAI_MODEL', default='gpt-4o-mini')

# Groq AI Configuration (alternative to Gemini - higher rate limits)
GROQ_API_KEY = config('GROQ_API_KEY', default='')
GROQ_MODEL = config('GROQ_MODEL', default='llama-3.3-70b-versatile')

# Ollama Configuration (local AI - no limits)
OLLAMA_BASE_URL = config('OLLAMA_BASE_URL', default='http://localhost:11434')
OLLAMA_MODEL = config('OLLAMA_MODEL', default='llama3.2')
OLLAMA_EMBED_MODEL = config('OLLAMA_EMBED_MODEL', default='nomic-embed-text')

# Process Memory Phase 1 — embeddings (lexical/off = empty vectors; ollama = Ollama API)
PROCESS_MEMORY_EMBEDDINGS = config('PROCESS_MEMORY_EMBEDDINGS', default='lexical')

# AI Provider Priority: free_first = groq → gemini → openai → ollama (PIP Phase 0)
AI_PROVIDER = config('AI_PROVIDER', default='free_first')  # free_first, auto, gemini, groq, openai, ollama

# =============================================================================
# FEATURE FLAGS - AI MODULES
# =============================================================================

# Tarot Holístico AI - Interpretaciones simbólicas educativas (NO clínicas)
# Habilita los endpoints /api/ai/tarot/* para interpretaciones holísticas
# Default: False (activar cuando el sistema esté listo para producción)
AI_TAROT_ENABLED = config('AI_TAROT_ENABLED', default=True, cast=bool)

# PIP Phase 2 — governed assistance (inference only, no training)
AI_KABBALAH_ENABLED = config('AI_KABBALAH_ENABLED', default=True, cast=bool)
AI_BIOEMOTION_DRAFT_ENABLED = config('AI_BIOEMOTION_DRAFT_ENABLED', default=True, cast=bool)

# Astrology Kerykeion - AI snippets (therapist in-session guidance)
# When enabled, the backend may generate short AI-written (non-verbatim) summaries
# for curated Sefaria references.
KERYKEION_AI_SNIPPETS_ENABLED = config('KERYKEION_AI_SNIPPETS_ENABLED', default=False, cast=bool)
ASTRO_MULTITECH_ENABLED = config('ASTRO_MULTITECH_ENABLED', default=True, cast=bool)
KERYKEION_AI_SNIPPETS_MODEL = config('KERYKEION_AI_SNIPPETS_MODEL', default='')

# PIP Process Memory — vector retrieval backend (Phase 1 step 3 scaffold)
# lexical: token overlap on ProcessSnapshot (default, no pgvector)
# pgvector: EmbeddingChunk cosine search (NotImplementedError until ops deploys extension)
PROCESS_MEMORY_VECTOR_BACKEND = config('PROCESS_MEMORY_VECTOR_BACKEND', default='lexical')
