export interface SephirothArcanaMapping {
  arcana: string;
  number: number;
  hebrewLetter: string;
  gematria: number;
  path: string;
  sefirot: [string, string];
  sources: string[];
}

export const SEPHIROTH_MAJOR_ARCANA: SephirothArcanaMapping[] = [
  {
    arcana: 'The Fool',
    number: 0,
    hebrewLetter: 'Aleph',
    gematria: 1,
    path: 'Kether-Chokmah',
    sefirot: ['Kether', 'Chokmah'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Magician',
    number: 1,
    hebrewLetter: 'Beth',
    gematria: 2,
    path: 'Kether-Binah',
    sefirot: ['Kether', 'Binah'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The High Priestess',
    number: 2,
    hebrewLetter: 'Gimel',
    gematria: 3,
    path: 'Kether-Tiphareth',
    sefirot: ['Kether', 'Tiphareth'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Empress',
    number: 3,
    hebrewLetter: 'Daleth',
    gematria: 4,
    path: 'Chokmah-Binah',
    sefirot: ['Chokmah', 'Binah'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Emperor',
    number: 4,
    hebrewLetter: 'Heh',
    gematria: 5,
    path: 'Chokmah-Tiphareth',
    sefirot: ['Chokmah', 'Tiphareth'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Hierophant',
    number: 5,
    hebrewLetter: 'Vav',
    gematria: 6,
    path: 'Chokmah-Chesed',
    sefirot: ['Chokmah', 'Chesed'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Lovers',
    number: 6,
    hebrewLetter: 'Zayin',
    gematria: 7,
    path: 'Binah-Tiphareth',
    sefirot: ['Binah', 'Tiphareth'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Chariot',
    number: 7,
    hebrewLetter: 'Cheth',
    gematria: 8,
    path: 'Binah-Geburah',
    sefirot: ['Binah', 'Geburah'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'Strength',
    number: 8,
    hebrewLetter: 'Teth',
    gematria: 9,
    path: 'Chesed-Geburah',
    sefirot: ['Chesed', 'Geburah'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Hermit',
    number: 9,
    hebrewLetter: 'Yod',
    gematria: 10,
    path: 'Chesed-Tiphareth',
    sefirot: ['Chesed', 'Tiphareth'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'Wheel of Fortune',
    number: 10,
    hebrewLetter: 'Kaph',
    gematria: 20,
    path: 'Chesed-Netzach',
    sefirot: ['Chesed', 'Netzach'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'Justice',
    number: 11,
    hebrewLetter: 'Lamed',
    gematria: 30,
    path: 'Geburah-Tiphareth',
    sefirot: ['Geburah', 'Tiphareth'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Hanged Man',
    number: 12,
    hebrewLetter: 'Mem',
    gematria: 40,
    path: 'Geburah-Hod',
    sefirot: ['Geburah', 'Hod'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'Death',
    number: 13,
    hebrewLetter: 'Nun',
    gematria: 50,
    path: 'Tiphareth-Netzach',
    sefirot: ['Tiphareth', 'Netzach'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'Temperance',
    number: 14,
    hebrewLetter: 'Samekh',
    gematria: 60,
    path: 'Tiphareth-Yesod',
    sefirot: ['Tiphareth', 'Yesod'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Devil',
    number: 15,
    hebrewLetter: 'Ayin',
    gematria: 70,
    path: 'Tiphareth-Hod',
    sefirot: ['Tiphareth', 'Hod'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Tower',
    number: 16,
    hebrewLetter: 'Peh',
    gematria: 80,
    path: 'Netzach-Hod',
    sefirot: ['Netzach', 'Hod'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Star',
    number: 17,
    hebrewLetter: 'Tsadi',
    gematria: 90,
    path: 'Netzach-Yesod',
    sefirot: ['Netzach', 'Yesod'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Moon',
    number: 18,
    hebrewLetter: 'Qoph',
    gematria: 100,
    path: 'Netzach-Malkuth',
    sefirot: ['Netzach', 'Malkuth'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The Sun',
    number: 19,
    hebrewLetter: 'Resh',
    gematria: 200,
    path: 'Hod-Yesod',
    sefirot: ['Hod', 'Yesod'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'Judgement',
    number: 20,
    hebrewLetter: 'Shin',
    gematria: 300,
    path: 'Hod-Malkuth',
    sefirot: ['Hod', 'Malkuth'],
    sources: ['Tarot of the Sephiroth'],
  },
  {
    arcana: 'The World',
    number: 21,
    hebrewLetter: 'Tav',
    gematria: 400,
    path: 'Yesod-Malkuth',
    sefirot: ['Yesod', 'Malkuth'],
    sources: ['Tarot of the Sephiroth'],
  },
];
