"""
Script para inicializar los módulos de tests en la base de datos
"""
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from api.test_models import TestModule
from api.mcmi4_signal_public_name import (
    MCMI4_SIGNAL_PUBLIC_DESCRIPTION,
    MCMI4_SIGNAL_PUBLIC_NAME,
)

HOLISTIC_LEGACY_OVERRIDES = {
    "phq-9": ("Pulse Resonance Mirror", "emotional_balance"),
    "bdi-ii": ("Dawn Reflection Index", "emotional_balance"),
    "gad-7": ("Calm Alignment Gauge", "anxiety_balance"),
    "bai": ("Stillness Resonance Inventory", "anxiety_balance"),
    "stai": ("Presence Balance Compass", "anxiety_balance"),
    "isi": ("Dreamflow Attunement", "sleep_harmony"),
    "insomnia-index": ("Restoration Rhythm Index", "sleep_harmony"),
    "ptsd-check": ("Soul Echo Release", "trauma_recovery"),
    "ptsd": ("Soul Echo Release", "trauma_recovery"),
    "ptsd-pcl5": ("Soul Story Harmonizer", "trauma_recovery"),
    "ocd-screen": ("Ritual Flow Snapshot", "ritual_balance"),
    "adhd-adult": ("Attention Flow Compass", "attention_clarity"),
    "adhd": ("Attention Flow Compass", "attention_clarity"),
    "substance-use": ("Sustenance Relationship Mirror", "substance_reconciliation"),
    "substance": ("Sustenance Relationship Mirror", "substance_reconciliation"),
    "eating-disorder": ("Abundance Relationship Mirror", "abundance_relations"),
    "eating": ("Abundance Relationship Mirror", "abundance_relations"),
    "scl90": ("Soul Symmetry Lens", "soul_alignment"),
    "scl-90": ("Soul Symmetry Lens", "soul_alignment"),
    "scl-90-r": ("Soul Symmetry Lens", "soul_alignment"),
    "mcmi-iv": ("Persona Pattern Atlas", "personality_mosaic"),
    "scid5": ("Structural Insight Dialogue", "personality_mosaic"),
    "scid-5-rv": ("Structural Insight Dialogue", "personality_mosaic"),
    "pai": ("Persona Alignment Compass", "persona_alignment"),
    "professional-pai": ("Persona Alignment Compass", "persona_alignment"),
}

TECHNICAL_TEST_PREFIXES = ("dbg-test", "lock-test", "smoke-test")

def initialize_tests():
    """Crea los módulos de tests iniciales"""
    
    tests_data = [
        {
            'code': 'basic-analysis',
            'name': 'Análisis Cabalístico Básico',
            'description': 'Análisis fundamental de tu nombre y fecha de nacimiento. Descubre tu número de destino, alma y personalidad.',
            'test_type': 'basic',
            'required_access_level': 'free',
            'icon': '📊',
            'order': 1,
            'estimated_duration': 5,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,  # Ilimitado
        },
        {
            'code': 'complete-numerology',
            'name': 'Numerología Completa',
            'description': 'Análisis profundo de todos tus números: destino, alma, personalidad, madurez, karmas y más.',
            'test_type': 'numerology',
            'required_access_level': 'personal',
            'icon': '🔢',
            'order': 2,
            'estimated_duration': 15,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': 10,  # 10 usos mensuales para plan personal
        },
        {
            'code': 'couple-compatibility',
            'name': 'Compatibilidad de Pareja',
            'description': 'Analiza la compatibilidad numerológica entre dos personas. Ideal para relaciones de pareja.',
            'test_type': 'compatibility',
            'required_access_level': 'personal',
            'icon': '💑',
            'order': 3,
            'estimated_duration': 10,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': 5,
        },
        {
            'code': 'career-guidance',
            'name': 'Orientación Profesional',
            'description': 'Descubre tus talentos naturales y las profesiones más adecuadas según tu numerología.',
            'test_type': 'career',
            'required_access_level': 'personal',
            'icon': '💼',
            'order': 4,
            'estimated_duration': 12,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': 5,
        },
        {
            'code': 'spiritual-path',
            'name': 'Camino Espiritual',
            'description': 'Explora tu propósito espiritual y las lecciones de vida que debes aprender.',
            'test_type': 'spiritual',
            'required_access_level': 'professional',
            'icon': '🕉️',
            'order': 5,
            'estimated_duration': 20,
            'available_for_therapists': True,
            'available_for_personal': False,  # Solo terapeutas
            'uses_per_month': None,  # Ilimitado para profesionales
        },
        {
            'code': 'professional-pai',
            'name': 'PAI - Evaluación Profesional',
            'description': 'Inventario de la personalidad (PAI) para evaluación clínica profesional.',
            'test_type': 'pai',
            'required_access_level': 'professional',
            'icon': '📋',
            'order': 6,
            'estimated_duration': 25,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'health-wellness',
            'name': 'Salud y Bienestar',
            'description': 'Análisis de aspectos relacionados con tu salud física y emocional según la numerología.',
            'test_type': 'health',
            'required_access_level': 'professional',
            'icon': '🏥',
            'order': 6,
            'estimated_duration': 15,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
        },
        {
            'code': 'financial-abundance',
            'name': 'Abundancia Financiera',
            'description': 'Descubre tus ciclos financieros y cómo atraer prosperidad según tu numerología.',
            'test_type': 'financial',
            'required_access_level': 'professional',
            'icon': '💰',
            'order': 7,
            'estimated_duration': 12,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': 3,
        },
        {
            'code': 'family-relations',
            'name': 'Relaciones Familiares',
            'description': 'Análisis de la dinámica familiar y compatibilidad entre miembros de la familia.',
            'test_type': 'family',
            'required_access_level': 'premium',
            'icon': '👨‍👩‍👧‍👦',
            'order': 8,
            'estimated_duration': 18,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
        },
        {
            'code': 'life-purpose',
            'name': 'Propósito de Vida',
            'description': 'Descubre tu misión de vida y cómo cumplir tu propósito en este plano terrenal.',
            'test_type': 'purpose',
            'required_access_level': 'premium',
            'icon': '🎯',
            'order': 9,
            'estimated_duration': 25,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
        },
        {
            'code': 'past-lives',
            'name': 'Vidas Pasadas – Exploración de Memorias del Alma',
            'description': (
                'Exploración simbólica y no diagnóstica de patrones, afinidades y memorias del alma '
                'que pueden iluminar tu presente.'
            ),
            'test_type': 'past_life',
            'required_access_level': 'premium',
            'icon': '🔮',
            'order': 10,
            'estimated_duration': 20,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': 2,
        },
        # Diagnostic modules (clinical tools for therapists)
        {
            'code': 'bdi-ii',
            'name': 'BDI-II - Inventario de Depresión',
            'description': 'Inventario de Depresión de Beck (BDI-II) para evaluación clínica. 21 ítems, alertas de riesgo suicida y recomendaciones.',
            'test_type': 'bdi',
            'required_access_level': 'professional',
            'icon': '🧠',
            'order': 11,
            'estimated_duration': 10,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'bai',
            'name': 'BAI - Inventario de Ansiedad de Beck',
            'description': 'Inventario de Ansiedad de Beck (BAI). Evalúa ansiedad somática y cognitiva, detecta síntomas de pánico.',
            'test_type': 'bai',
            'required_access_level': 'professional',
            'icon': '⚠️',
            'order': 12,
            'estimated_duration': 10,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'phq-9',
            'name': 'PHQ-9',
            'description': 'PHQ-9 - Screening de depresión para evaluación rápida y seguimiento.',
            'test_type': 'diagnostic',
            'required_access_level': 'professional',
            'icon': '🧾',
            'order': 13,
            'estimated_duration': 5,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
        },
        {
            'code': 'gad-7',
            'name': 'GAD-7',
            'description': 'GAD-7 - Cuestionario breve para trastorno de ansiedad generalizada.',
            'test_type': 'diagnostic',
            'required_access_level': 'professional',
            'icon': '😰',
            'order': 14,
            'estimated_duration': 5,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
        },
        {
            'code': 'ptsd-check',
            'name': 'PTSD Check',
            'description': 'Screening para trastorno por estrés postraumático.',
            'test_type': 'diagnostic',
            'required_access_level': 'professional',
            'icon': '🔥',
            'order': 15,
            'estimated_duration': 8,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        # In-house holistic screenings (non-licensed)
        {
            'code': 'wellness',
            'name': 'Wellness Assessment',
            'description': 'Cuestionario interno (no médico) para mapear hábitos, energía, estrés y autocuidado. Orientado a bienestar integral y plan de acciones.',
            'test_type': 'holistic_screening',
            'required_access_level': 'free',
            'icon': '🌿',
            'order': 15,
            'estimated_duration': 8,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
            'requires_license': False,
        },
        {
            'code': 'screening-general',
            'name': 'Screening Psicológico General',
            'description': 'Cuestionario interno (no diagnóstico) para detectar áreas de malestar, funcionamiento diario y recursos. Útil como mapa inicial para conversación terapéutica.',
            'test_type': 'holistic_screening',
            'required_access_level': 'free',
            'icon': '🧭',
            'order': 16,
            'estimated_duration': 10,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
            'requires_license': False,
        },
        {
            'code': 'stress',
            'name': 'Estrés — Carga y regulación',
            'description': 'Wellness orientativo (no diagnóstico) para explorar carga de estrés, regulación y recursos.',
            'test_type': 'wellness',
            'required_access_level': 'free',
            'icon': '🧘',
            'order': 16,
            'estimated_duration': 8,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
            'requires_license': False,
        },
        {
            'code': 'anxiety-state-trait',
            'name': 'Ansiedad — Estado y rasgo',
            'description': 'Wellness orientativo para mapear la ansiedad del presente y la tendencia personal.',
            'test_type': 'wellness',
            'required_access_level': 'free',
            'icon': '⚖️',
            'order': 17,
            'estimated_duration': 8,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
            'requires_license': False,
        },
        {
            'code': 'ocd-screen',
            'name': 'OCD Screen',
            'description': 'Cuestionario de cribado para transtorno obsesivo-compulsivo (OCD).',
            'test_type': 'diagnostic',
            'required_access_level': 'professional',
            'icon': '🧩',
            'order': 16,
            'estimated_duration': 8,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'insomnia-index',
            'name': 'Insomnia Index',
            'description': 'Evaluación del insomnio y calidad del sueño.',
            'test_type': 'diagnostic',
            'required_access_level': 'professional',
            'icon': '🌙',
            'order': 17,
            'estimated_duration': 6,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
        },
        {
            'code': 'nutrition',
            'name': 'Alimentación — Relación y hábitos',
            'description': 'Evaluación wellness (no diagnóstico) sobre hábitos y relación con la alimentación.',
            'test_type': 'holistic_screening',
            'required_access_level': 'free',
            'icon': '🥗',
            'order': 18,
            'estimated_duration': 7,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
        },
        {
            'code': 'adhd-adult',
            'name': 'ADHD - Adult Screening',
            'description': 'Screening para TDAH en adultos (síntomas actuales y seguimiento).',
            'test_type': 'diagnostic',
            'required_access_level': 'professional',
            'icon': '⚡',
            'order': 18,
            'estimated_duration': 8,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'substance-use',
            'name': 'Substance Use Screening',
            'description': 'Cribado de consumo de sustancias y riesgo asociado.',
            'test_type': 'diagnostic',
            'required_access_level': 'professional',
            'icon': '🍷',
            'order': 19,
            'estimated_duration': 8,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'eating-disorder',
            'name': 'Eating Disorder Screen',
            'description': 'Cribado para trastornos de la conducta alimentaria.',
            'test_type': 'diagnostic',
            'required_access_level': 'professional',
            'icon': '🥗',
            'order': 20,
            'estimated_duration': 8,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'scl90',
            'name': 'SCL-90 - Screening Holistico',
            'description': 'Version holistica tipo Wellness del SCL-90 para evaluar sintomas generales sin diagnostico.',
            'test_type': 'wellness',
            'required_access_level': 'free',
            'icon': '??',
            'order': 21,
            'estimated_duration': 12,
            'available_for_therapists': False,
            'available_for_personal': True,
            'uses_per_month': None,
            'requires_license': False,
            'license_info': '',
        },
        {
            'code': 'mcmi-iv',
            'name': 'MCMI-IV - Inventario Multiaxial de Millon',
            'description': 'MCMI-IV para evaluación de personalidad (placeholder). Use contenido licenciado en producción.',
            'test_type': 'mcmi-iv',
            'required_access_level': 'professional',
            'icon': '🧩',
            'order': 23,
            'estimated_duration': 25,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
            'requires_license': True,
            'license_info': 'MCMI-IV es un instrumento con derechos de autor. Debes tener licencia válida para administrarlo en esta plataforma.'
        },
        {
            'code': 'life-purpose',
            'name': 'Propósito de Vida y Sentido Vital',
            'description': 'Explora la claridad de dirección, el sentido de trascendencia y la conexión con el propósito vital. (Mundo de Atzilut)',
            'test_type': 'purpose',
            'required_access_level': 'professional',
            'icon': '🎯',
            'order': 9,
            'estimated_duration': 15,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'cognitive-map',
            'name': 'Mapa Cognitivo y Narrativa',
            'description': 'Evalúa la flexibilidad mental, los estilos de pensamiento y la coherencia de la narrativa personal. (Mundo de Beriá)',
            'test_type': 'holistic_screening',
            'required_access_level': 'professional',
            'icon': '🧩',
            'order': 25,
            'estimated_duration': 12,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'belief-system',
            'name': 'Sistema de Creencias',
            'description': 'Mapeo de creencias potenciadoras y limitantes que configuran la percepción de la realidad. (Mundo de Beriá)',
            'test_type': 'holistic_screening',
            'required_access_level': 'professional',
            'icon': '🕸️',
            'order': 26,
            'estimated_duration': 15,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'emotional-literacy',
            'name': 'Alfabetización Emocional',
            'description': 'Evalúa la capacidad de reconocer, nombrar y regular procesos emocionales internos. (Mundo de Ietzirá)',
            'test_type': 'holistic_screening',
            'required_access_level': 'professional',
            'icon': '🎭',
            'order': 27,
            'estimated_duration': 15,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'attachment-style',
            'name': 'Vínculo y Estilo de Apego',
            'description': 'Explora los patrones de vinculación afectiva y la seguridad en las relaciones. (Mundo de Ietzirá)',
            'test_type': 'holistic_screening',
            'required_access_level': 'professional',
            'icon': '🔗',
            'order': 28,
            'estimated_duration': 20,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'daily-rhythm',
            'name': 'Hábitos y Ritmo Vital',
            'description': 'Evaluación de la regularidad en las rutinas básicas y el equilibrio entre acción y descanso. (Mundo de Asiá)',
            'test_type': 'holistic_screening',
            'required_access_level': 'professional',
            'icon': '⌚',
            'order': 29,
            'estimated_duration': 10,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'somatic-awareness',
            'name': 'Registro Somático y Presencia',
            'description': 'Evalúa la conexión con las señales del cuerpo, la tensión física y la presencia en el aquí y ahora. (Mundo de Asiá)',
            'test_type': 'holistic_screening',
            'required_access_level': 'professional',
            'icon': '🧘',
            'order': 30,
            'estimated_duration': 10,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
        },
        {
            'code': 'mcmi4-mystic',
            'name': 'MCMI-4-Mystic - Inventario Multiaxial Cósmico',
            'description': 'Inventario comprensivo de 195 ítems que mapea la personalidad del alma a través de los 4 Mundos Cabalísticos (Atzilut, Briah, Yetzirah, Assiah). Sistema modular con rotación inteligente de preguntas. **Gestionado exclusivamente desde SWM dedicado.**',
            'test_type': 'holistic_screening',
            'required_access_level': 'professional',
            'icon': '🌌',
            'order': 999,  # High order number to push to bottom of lists
            'estimated_duration': 45,
            'available_for_therapists': False,  # Not shown in therapist catalog
            'available_for_personal': False,    # Not shown in personal catalog
            'uses_per_month': None,
            'is_assignable': True,  # Can still be assigned via SWM
            'requires_license': False,
        },
        {
            'code': 'mcmi4-signal',
            'name': MCMI4_SIGNAL_PUBLIC_NAME,
            'description': MCMI4_SIGNAL_PUBLIC_DESCRIPTION,
            'test_type': 'holistic_screening',
            'required_access_level': 'free',
            'icon': '🧭',
            'order': 998,
            'estimated_duration': 5,
            'available_for_therapists': True,
            'available_for_personal': True,
            'uses_per_month': None,
            'is_assignable': True,
            'requires_license': False,
            'public_name': MCMI4_SIGNAL_PUBLIC_NAME,
        },
        {
            'code': 'scid5',
            'name': 'SCID-5-RV - Entrevista DSM-5',
            'description': 'SCID-5-RV - Entrevista clínica estructurada para DSM-5 (se requiere adaptación clínica).',
            'test_type': 'scid5',
            'required_access_level': 'professional',
            'icon': '🔎',
            'order': 24,
            'estimated_duration': 60,
            'available_for_therapists': True,
            'available_for_personal': False,
            'uses_per_month': None,
            'requires_license': True,
            'license_info': 'SCID-5-RV es un instrumento protegido. Confirmar licencia y capacitación antes de uso.'
        },
    ]

    for test_data in tests_data:
        code = test_data['code']
        override = HOLISTIC_LEGACY_OVERRIDES.get(code)
        if override:
            test_data['name'] = override[0]
            test_data['public_name'] = override[0]
            test_data['canonical_family'] = override[1]
        else:
            test_data.setdefault('public_name', test_data['name'])
        test_data.setdefault('domain', 'holistic')

    created_count = 0
    updated_count = 0
    
    for test_data in tests_data:
        test, created = TestModule.objects.update_or_create(
            code=test_data['code'],
            defaults=test_data
        )
        
        if created:
            created_count += 1
            print(f"✓ Creado: {test.name}")
        else:
            updated_count += 1
            print(f"↻ Actualizado: {test.name}")
    
    for prefix in TECHNICAL_TEST_PREFIXES:
        TestModule.objects.filter(code__startswith=prefix).update(
            domain="technical",
            is_internal=True,
            is_assignable=False,
            canonical_family="technical_operations",
            public_name="Hidden Operational Probe",
        )

    print(f"\n{'='*50}")
    print(f"Tests creados: {created_count}")
    print(f"Tests actualizados: {updated_count}")
    print(f"Total tests: {TestModule.objects.count()}")
    print(f"{'='*50}\n")

if __name__ == '__main__':
    print("Inicializando módulos de tests...\n")
    initialize_tests()
    print("¡Listo!")
