# Generated by Django 5.2.9 on 2026-01-01 17:18

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolicReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_id', models.CharField(help_text='Symbolic system id (e.g. thoth).', max_length=50)),
                ('reading_type', models.CharField(choices=[('educational', 'Educational')], default='educational', help_text='Reading type (Phase 3: educational mock only).', max_length=32)),
                ('content', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Serialized reading payload (mock result).')),
                ('consent_mode', models.CharField(choices=[('no_store', 'No store'), ('store_anonymized', 'Store anonymized'), ('store_with_consent', 'Store with consent')], max_length=32)),
                ('consent_version', models.CharField(blank=True, max_length=64, null=True)),
                ('consent_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_trace', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Audit metadata (swm version, phase, flags, source, disclaimer).')),
                ('consultant', models.ForeignKey(blank=True, help_text='Optional consultant user (nullable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symbolic_readings_as_consultant', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(help_text='Owner therapist (non-clinical symbolic artifact).', on_delete=django.db.models.deletion.CASCADE, related_name='symbolic_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Symbolic Reading',
                'verbose_name_plural': 'Symbolic Readings',
                'ordering': ['-created_at'],
            },
        ),
    ]
