# Generated by Django 5.2.9 on 2026-01-17 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='MCMI-4 Místico', max_length=200)),
                ('code', models.CharField(default='MCMI4_MYSTIC', max_length=50, unique=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Workspace Definition',
                'verbose_name_plural': 'Workspace Definitions',
                'db_table': 'workspace_definitions',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('sealed', 'Sealed'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='created', max_length=20)),
                ('mcmi4_source_data_id', models.CharField(help_text='Reference to MCMI-4 data', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('creator_user', models.ForeignKey(help_text='User who created this workspace (typically therapist)', on_delete=django.db.models.deletion.PROTECT, related_name='workspaces_created', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(help_text='User whose MCMI-4 data is being analyzed (NOT necessarily the executor)', on_delete=django.db.models.deletion.PROTECT, related_name='workspaces_as_subject', to=settings.AUTH_USER_MODEL)),
                ('workspace_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='swm_mcmi4.workspacedefinition')),
            ],
            options={
                'verbose_name': 'Workspace Instance',
                'verbose_name_plural': 'Workspace Instances',
                'db_table': 'workspace_instances',
            },
        ),
        migrations.CreateModel(
            name='WorkspacePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_type', models.CharField(choices=[('executor', 'Executor'), ('observer', 'Observer'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_permissions', to=settings.AUTH_USER_MODEL)),
                ('workspace_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='swm_mcmi4.workspaceinstance')),
            ],
            options={
                'verbose_name': 'Workspace Permission',
                'verbose_name_plural': 'Workspace Permissions',
                'db_table': 'workspace_permissions',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session_state', models.JSONField(blank=True, default=dict, help_text='Progress, decisions, context')),
                ('interactions_count', models.IntegerField(default=0)),
                ('current_phase', models.CharField(choices=[('discovery', 'Discovery'), ('mapping', 'Mapping'), ('interpretation', 'Interpretation'), ('synthesis', 'Synthesis')], default='discovery', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('executor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspace_sessions_executed', to=settings.AUTH_USER_MODEL)),
                ('workspace_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='swm_mcmi4.workspaceinstance')),
            ],
            options={
                'verbose_name': 'Workspace Session',
                'verbose_name_plural': 'Workspace Sessions',
                'db_table': 'workspace_sessions',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Action type: created, started, sealed, etc.', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Contextual details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='swm_mcmi4.workspaceinstance')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='swm_mcmi4.workspacesession')),
            ],
            options={
                'verbose_name': 'Workspace Audit Log',
                'verbose_name_plural': 'Workspace Audit Logs',
                'db_table': 'workspace_audit_logs',
                'permissions': [('view_audit_log', 'Can view audit logs')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('symbolic_map', 'Symbolic Map'), ('narrative', 'Narrative'), ('hypothesis', 'Hypothesis'), ('synthesis_report', 'Synthesis Report'), ('archetype_profile', 'Archetype Profile')], max_length=50)),
                ('content', models.JSONField(help_text='Artifact content (immutable post-seal)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sealed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='swm_mcmi4.workspaceinstance')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='swm_mcmi4.workspacesession')),
            ],
            options={
                'verbose_name': 'Workspace Artifact',
                'verbose_name_plural': 'Workspace Artifacts',
                'db_table': 'workspace_artifacts',
            },
        ),
        migrations.AddIndex(
            model_name='workspaceinstance',
            index=models.Index(fields=['workspace_definition', 'status'], name='workspace_i_workspa_9ddd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinstance',
            index=models.Index(fields=['subject_user', 'status'], name='workspace_i_subject_a38b71_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinstance',
            index=models.Index(fields=['creator_user', '-created_at'], name='workspace_i_creator_e0e276_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacepermission',
            index=models.Index(fields=['workspace_instance', 'user', 'is_active'], name='workspace_p_workspa_7cf79c_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacepermission',
            index=models.Index(fields=['user', 'is_active'], name='workspace_p_user_id_4610ab_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacesession',
            index=models.Index(fields=['workspace_instance', 'is_active'], name='workspace_s_workspa_0792f2_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacesession',
            index=models.Index(fields=['executor_user', '-started_at'], name='workspace_s_executo_2ece64_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace_instance',), name='unique_active_session_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['workspace_instance', '-timestamp'], name='workspace_a_workspa_622161_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='workspace_a_user_id_14089a_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceartifact',
            index=models.Index(fields=['workspace_instance', 'artifact_type'], name='workspace_a_workspa_0648c8_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceartifact',
            index=models.Index(fields=['session'], name='workspace_a_session_2d5594_idx'),
        ),
    ]
