# Generated by Django 5.2.9 on 2025-12-26 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59'), (60, '60'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (66, '66'), (67, '67'), (68, '68'), (69, '69'), (70, '70'), (71, '71'), (72, '72')], help_text='ID fijo del ángel (1-72) según tradición cabalística', primary_key=True, serialize=False)),
                ('nombre_hebreo', models.CharField(help_text='Nombre del ángel en hebreo', max_length=100)),
                ('transliteracion', models.CharField(help_text='Transliteración del nombre hebreo', max_length=100)),
                ('versiculo', models.CharField(help_text='Referencia bíblica asociada al ángel', max_length=200)),
                ('sefira', models.CharField(help_text='Sefirá del Árbol de la Vida asociada', max_length=50)),
                ('cualidades', models.JSONField(default=list, help_text='Lista de cualidades simbólicas asociadas')),
                ('correccion', models.JSONField(default=list, help_text='Aspectos de corrección simbólica')),
                ('sombra', models.JSONField(default=list, help_text='Aspectos de sombra simbólica')),
                ('keywords', models.JSONField(default=list, help_text='Palabras clave para consultas y búsquedas')),
            ],
            options={
                'verbose_name': 'Ángel',
                'verbose_name_plural': 'Ángeles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AngelPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('natal', 'Natal'), ('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], help_text='Tipo de periodo temporal', max_length=20)),
                ('start_date', models.DateField(help_text='Fecha de inicio del periodo')),
                ('end_date', models.DateField(help_text='Fecha de fin del periodo')),
                ('weight', models.FloatField(default=1.0, help_text='Peso o importancia del periodo (0.0-1.0)')),
                ('angel', models.ForeignKey(help_text='Ángel asociado al periodo', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='angels_engine.angel')),
            ],
            options={
                'verbose_name': 'Periodo Angelical',
                'verbose_name_plural': 'Periodos Angelicales',
                'ordering': ['start_date', 'type'],
                'unique_together': {('angel', 'type', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='PersonAngelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(help_text='Fecha de nacimiento para cálculo natal')),
                ('notes', models.TextField(blank=True, help_text='Notas descriptivas simbólicas (no clínicas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('natal_angel', models.ForeignKey(blank=True, help_text='Ángel natal calculado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natal_profiles', to='angels_engine.angel')),
                ('person', models.ForeignKey(help_text='Persona asociada al perfil angelical', on_delete=django.db.models.deletion.CASCADE, related_name='angel_profiles', to=settings.AUTH_USER_MODEL)),
                ('secondary_angels', models.ManyToManyField(blank=True, help_text='Ángeles secundarios asociados', related_name='secondary_profiles', to='angels_engine.angel')),
            ],
            options={
                'verbose_name': 'Perfil Angelical',
                'verbose_name_plural': 'Perfiles Angelicales',
                'ordering': ['-created_at'],
                'unique_together': {('person', 'birth_date')},
            },
        ),
    ]
