export type AqQuestion = { id: string; text: string };

export const aqKabbalahDefinition = {
  code: 'aq_kabbalah',
  name: 'AQ-Kabbalah — Espectro de Conciencia Cabalístico',
  purpose: 'Exploración simbólica del patrón de conciencia y conexión relacional',
  estimated_time_minutes: 10,
  scale: {
    options: [
      { value: 0, label: 'En desacuerdo' },
      { value: 1, label: 'De acuerdo' },
    ],
  },
  questions: [
    { id: 'q1', text: 'Prefiero el tejido del encuentro con otros antes que caminar solo por el sendero interior.' },
    { id: 'q2', text: 'Cuando encuentro una forma de hacer algo, tiendo a repetirla de la misma manera una y otra vez.' },
    { id: 'q3', text: 'Cuando intento imaginar algo, surge en mí con facilidad una imagen vívida y clara.' },
    { id: 'q4', text: 'Con frecuencia me sumerjo en una sola corriente de atención hasta perder conciencia del entorno.' },
    { id: 'q5', text: 'Con frecuencia percibo sonidos sutiles que pasan desapercibidos para quienes me rodean.' },
    { id: 'q6', text: 'Suelo reparar en secuencias de signos —matrículas, códigos, patrones visuales— de manera espontánea.' },
    { id: 'q7', text: 'Otros me señalan con frecuencia que algo que expresé resultó descortés, aunque yo no lo percibí de ese modo.' },
    { id: 'q8', text: 'Al leer un relato, construyo con facilidad la imagen interior de sus personajes.' },
    { id: 'q9', text: 'Los registros de fechas, ciclos y momentos temporales me resultan especialmente fascinantes.' },
    { id: 'q10', text: 'En un encuentro colectivo, puedo seguir el hilo de varias conversaciones simultáneamente.' },
    { id: 'q11', text: 'Me muevo con fluidez en los espacios donde se entrelazan las energías de otras personas.' },
    { id: 'q12', text: 'Tiendo a percibir detalles que otros no registran.' },
    { id: 'q13', text: 'Siento mayor afinidad con el silencio de la biblioteca que con el bullicio de una celebración.' },
    { id: 'q14', text: 'Inventar y narrar historias me resulta algo completamente natural.' },
    { id: 'q15', text: 'Me siento atraído hacia las almas más que hacia los objetos y las cosas.' },
    { id: 'q16', text: 'Tengo campos de interés muy profundos y me genera malestar no poder habitarlos libremente.' },
    { id: 'q17', text: 'Disfruto de la conversación ligera y espontánea en el encuentro cotidiano.' },
    { id: 'q18', text: 'En el diálogo, a veces me cuesta ceder el espacio para que el otro tome la palabra.' },
    { id: 'q19', text: 'El lenguaje de los números y sus patrones me atrae de modo especial.' },
    { id: 'q20', text: 'Al leer un relato, me cuesta descifrar las motivaciones internas de sus personajes.' },
    { id: 'q21', text: 'La ficción narrativa no despierta en mí un disfrute particular.' },
    { id: 'q22', text: 'Tejo nuevas conexiones del alma con dificultad.' },
    { id: 'q23', text: 'Percibo patrones y estructuras repetitivas en todo lo que observo.' },
    { id: 'q24', text: 'Prefiero la experiencia viva del teatro al orden estático de las colecciones y museos.' },
    { id: 'q25', text: 'Las alteraciones en el flujo habitual de mi día no me generan perturbación.' },
    { id: 'q26', text: 'Con frecuencia no sé cómo sostener el hilo de una conversación.' },
    { id: 'q27', text: 'Puedo descifrar con facilidad lo que no se dice en las palabras del otro.' },
    { id: 'q28', text: 'Suelo mantener mi atención en el conjunto más que en los pequeños detalles.' },
    { id: 'q29', text: 'Las cadenas de datos como secuencias numéricas no se fijan con facilidad en mi memoria.' },
    { id: 'q30', text: 'Los cambios sutiles en el ambiente o en la apariencia de otros no suelen llegar a mi conciencia.' },
    { id: 'q31', text: 'Percibo con claridad cuando mi interlocutor ha perdido el interés en lo que le comunico.' },
    { id: 'q32', text: 'Me resulta natural sostener varias corrientes de atención de forma simultánea.' },
    { id: 'q33', text: 'Cuando me comunico sin presencia directa, no siempre sé cuándo es mi turno de intervenir.' },
    { id: 'q34', text: 'Disfruto de la frescura de actuar sin planificar, siguiendo el impulso del momento.' },
    { id: 'q35', text: 'Suelo ser el último en captar el núcleo de un juego de palabras o una broma.' },
    { id: 'q36', text: 'Puedo discernir los estados interiores de otros simplemente al contemplar su presencia.' },
    { id: 'q37', text: 'Si hay una interrupción en mi camino, retorno al hilo de mi enfoque con facilidad.' },
    { id: 'q38', text: 'La conversación cotidiana y social fluye con naturalidad en mí.' },
    { id: 'q39', text: 'Otros me señalan que vuelvo repetidamente al mismo tema.' },
    { id: 'q40', text: 'De niño, disfrutaba de los juegos donde podía encarnar mundos imaginarios con otros.' },
    { id: 'q41', text: 'Me gusta acumular información sobre categorías de cosas, creando mi propia taxonomía interior.' },
    { id: 'q42', text: 'Me resulta difícil sumergirme de verdad en la perspectiva de otra persona desde adentro.' },
    { id: 'q43', text: 'Cuando participo en algo, prefiero haberlo trazado con cuidado de antemano.' },
    { id: 'q44', text: 'Los encuentros colectivos son momentos de júbilo y conexión para mí.' },
    { id: 'q45', text: 'Descifrar las intenciones ocultas del otro me resulta difícil.' },
    { id: 'q46', text: 'Las situaciones nuevas me generan inquietud interior.' },
    { id: 'q47', text: 'Me alegra abrirme al encuentro con almas que aún no conozco.' },
    { id: 'q48', text: 'Soy hábil para navegar las aguas del encuentro con tino y elegancia.' },
    { id: 'q49', text: 'Las fechas de nacimiento de quienes forman parte de mi mundo no permanecen grabadas en mí.' },
    { id: 'q50', text: 'Encarnar mundos de fantasía junto a niños en sus juegos me resulta algo natural.' },
  ] as AqQuestion[],
};
