# Generated by Django 5.2.9 on 2025-12-23 21:41

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0038_bioemotionalpatientbrief'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_datetime', models.DateTimeField(help_text='Birth date and time')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Birth latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Birth longitude', max_digits=9)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone string', max_length=100)),
                ('house_system', models.CharField(default='P', help_text='House system used (P=Placidus, K=Koch, etc.)', max_length=2)),
                ('zodiac_type', models.CharField(default='T', help_text='Zodiac type (T=Tropical, S=Sidereal)', max_length=1)),
                ('planets_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Calculated planet positions')),
                ('houses_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Calculated house cusps')),
                ('aspects_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Calculated aspects between planets')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, help_text='Calculation version')),
                ('patient', models.OneToOneField(help_text='Patient this natal chart belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='natal_chart', to='api.patient')),
            ],
            options={
                'verbose_name': 'Carta Natal',
                'verbose_name_plural': 'Cartas Natales',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
