# Generated by Django 5.2.9 on 2026-01-24 23:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(help_text='Alias o identificador (sin datos reales): "Abuelo P", "Tía M1"', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('relationship', models.CharField(choices=[('self', 'Consultante'), ('spouse', 'Cónyuge/Pareja'), ('sibling', 'Hermano/a'), ('half_sibling', 'Medio hermano/a'), ('twin', 'Gemelo/a'), ('father', 'Padre'), ('mother', 'Madre'), ('stepfather', 'Padrastro'), ('stepmother', 'Madrastra'), ('son', 'Hijo'), ('daughter', 'Hija'), ('stepson', 'Hijastro'), ('stepdaughter', 'Hijastra'), ('grandfather_paternal', 'Abuelo paterno'), ('grandmother_paternal', 'Abuela paterna'), ('grandfather_maternal', 'Abuelo materno'), ('grandmother_maternal', 'Abuela materna'), ('uncle_paternal', 'Tío paterno'), ('aunt_paternal', 'Tía paterna'), ('uncle_maternal', 'Tío materno'), ('aunt_maternal', 'Tía materna'), ('cousin', 'Primo/a'), ('great_grandparent', 'Bisabuelo/a'), ('other', 'Otro familiar')], help_text='Relación con el consultante', max_length=50)),
                ('generation', models.IntegerField(default=0, help_text='Generación relativa al consultante: 0=misma, -1=padres, -2=abuelos, +1=hijos')),
                ('birth_order', models.IntegerField(default=1, help_text='Orden de nacimiento entre hermanos', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('alive', 'Vivo/a'), ('deceased', 'Fallecido/a'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('significant_events', models.JSONField(blank=True, default=list, help_text='Lista de eventos significativos [{type, year, description}]')),
                ('characteristics', models.JSONField(blank=True, default=list, help_text='Características observadas: ["trabajador", "conflictivo", etc.]')),
                ('notes', models.TextField(blank=True, default='')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro Familiar',
                'verbose_name_plural': 'Miembros Familiares',
                'db_table': 'swm_transgenerational_family_members',
                'ordering': ['generation', 'birth_order'],
            },
        ),
        migrations.CreateModel(
            name='TransgenerationalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('created', 'Creada'), ('in_progress', 'En Progreso'), ('paused', 'Pausada'), ('closed', 'Cerrada'), ('archived', 'Archivada')], default='created', max_length=20)),
                ('genogram_data', models.JSONField(blank=True, default=dict, help_text='Estructura visual del genograma (posiciones, conexiones, etc.)')),
                ('session_notes', models.TextField(blank=True, default='')),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='Áreas de enfoque: ["lealtades", "secretos", "repeticiones"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(help_text='Usuario/paciente siendo explorado', on_delete=django.db.models.deletion.PROTECT, related_name='transgenerational_sessions_as_patient', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(help_text='Terapeuta que conduce la sesión', on_delete=django.db.models.deletion.PROTECT, related_name='transgenerational_sessions_as_therapist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Transgeneracional',
                'verbose_name_plural': 'Sesiones Transgeneracionales',
                'db_table': 'swm_transgenerational_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransgenerationalPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_name', models.CharField(help_text='Nombre descriptivo del patrón', max_length=200)),
                ('pattern_type', models.CharField(choices=[('loyalty', 'Lealtad invisible'), ('secret', 'Secreto familiar'), ('trauma', 'Trauma transgeneracional'), ('repetition', 'Repetición de patrones'), ('parentification', 'Parentificación'), ('exclusion', 'Exclusión familiar'), ('triangulation', 'Triangulación'), ('enmeshment', 'Fusión/Codependencia'), ('cutoff', 'Corte emocional'), ('projection', 'Proyección transgeneracional'), ('anniversary', 'Síndrome del aniversario'), ('replacement', 'Hijo de reemplazo'), ('ghost', 'Fantasma familiar'), ('debt', 'Deuda transgeneracional'), ('mission', 'Misión familiar'), ('sacrifice', 'Sacrificio sistémico'), ('other', 'Otro patrón')], max_length=30)),
                ('generations_affected', models.JSONField(blank=True, default=list, help_text='Lista de generaciones afectadas: [-2, -1, 0]')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción del patrón observado')),
                ('therapist_notes', models.TextField(blank=True, default='', help_text='Notas terapéuticas sobre el patrón')),
                ('is_acknowledged', models.BooleanField(default=False, help_text='El patrón ha sido reconocido por el consultante')),
                ('is_worked', models.BooleanField(default=False, help_text='Se ha trabajado terapéuticamente este patrón')),
                ('intensity', models.IntegerField(default=5, help_text='Intensidad del patrón (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members_involved', models.ManyToManyField(blank=True, related_name='patterns_involved', to='swm_transgenerational.familymember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='swm_transgenerational.transgenerationalsession')),
            ],
            options={
                'verbose_name': 'Patrón Transgeneracional',
                'verbose_name_plural': 'Patrones Transgeneracionales',
                'db_table': 'swm_transgenerational_patterns',
                'ordering': ['-intensity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyndromeMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('birth', 'Nacimiento'), ('death', 'Muerte'), ('marriage', 'Matrimonio'), ('divorce', 'Divorcio/Separación'), ('illness', 'Enfermedad grave'), ('accident', 'Accidente'), ('migration', 'Migración'), ('war', 'Guerra/Conflicto'), ('loss', 'Pérdida significativa'), ('abuse', 'Abuso/Violencia'), ('abandonment', 'Abandono'), ('adoption', 'Adopción'), ('miscarriage', 'Aborto/Pérdida gestacional'), ('suicide', 'Suicidio'), ('imprisonment', 'Encarcelamiento'), ('bankruptcy', 'Quiebra/Ruina'), ('success', 'Éxito significativo'), ('inheritance', 'Herencia'), ('secret_revealed', 'Revelación de secreto'), ('reconciliation', 'Reconciliación'), ('other', 'Otro evento')], max_length=30)),
                ('original_date', models.DateField(blank=True, help_text='Fecha original del evento (puede ser aproximada)', null=True)),
                ('original_year', models.IntegerField(blank=True, help_text='Año del evento original (si no se conoce fecha exacta)', null=True)),
                ('recurring_pattern', models.TextField(blank=True, default='', help_text='Descripción del patrón de recurrencia')),
                ('recurring_dates', models.JSONField(blank=True, default=list, help_text='Lista de fechas/años donde se repite: [{year, member_alias, event}]')),
                ('significance', models.TextField(blank=True, default='', help_text='Significado terapéutico de esta marca temporal')),
                ('therapist_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_member', models.ForeignKey(blank=True, help_text='Miembro original donde ocurrió el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_syndrome_marks', to='swm_transgenerational.familymember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syndrome_marks', to='swm_transgenerational.transgenerationalsession')),
            ],
            options={
                'verbose_name': 'Marca de Síndrome',
                'verbose_name_plural': 'Marcas de Síndrome',
                'db_table': 'swm_transgenerational_syndrome_marks',
                'ordering': ['original_date', 'original_year'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('marriage', 'Matrimonio'), ('partnership', 'Unión/Pareja'), ('divorce', 'Divorcio'), ('parent_child', 'Padre/Madre-Hijo'), ('sibling', 'Hermanos'), ('conflict', 'Conflicto'), ('cutoff', 'Corte relacional'), ('enmeshment', 'Fusión'), ('distant', 'Distancia emocional'), ('close', 'Cercanía'), ('abuse', 'Abuso'), ('caretaking', 'Cuidador')], max_length=30)),
                ('quality', models.CharField(choices=[('positive', 'Positiva'), ('negative', 'Negativa'), ('ambivalent', 'Ambivalente'), ('neutral', 'Neutral'), ('unknown', 'Desconocida')], default='neutral', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='swm_transgenerational.familymember')),
                ('member_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='swm_transgenerational.familymember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='swm_transgenerational.transgenerationalsession')),
            ],
            options={
                'verbose_name': 'Relación Familiar',
                'verbose_name_plural': 'Relaciones Familiares',
                'db_table': 'swm_transgenerational_family_relationships',
            },
        ),
        migrations.AddField(
            model_name='familymember',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='swm_transgenerational.transgenerationalsession'),
        ),
        migrations.CreateModel(
            name='TransgenerationalSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genogram_data', models.JSONField(default=dict, help_text='Estado del genograma en este momento')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='swm_transgenerational.transgenerationalsession')),
            ],
            options={
                'verbose_name': 'Snapshot Transgeneracional',
                'verbose_name_plural': 'Snapshots Transgeneracionales',
                'db_table': 'swm_transgenerational_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transgenerationalsession',
            index=models.Index(fields=['patient', 'status'], name='swm_transge_patient_8eef17_idx'),
        ),
        migrations.AddIndex(
            model_name='transgenerationalsession',
            index=models.Index(fields=['therapist', 'status'], name='swm_transge_therapi_de8b78_idx'),
        ),
        migrations.AddIndex(
            model_name='transgenerationalsession',
            index=models.Index(fields=['created_at'], name='swm_transge_created_d2fbc4_idx'),
        ),
    ]
