# Generated by Django 5.2.9 on 2026-01-19 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='MCMI-4 Reflection', max_length=200)),
                ('code', models.CharField(default='MCMI4_REFLECTION', max_length=50, unique=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reflection Workspace Definition',
                'verbose_name_plural': 'Reflection Workspace Definitions',
                'db_table': 'reflection_workspace_definitions',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sealed', 'Sealed')], default='draft', max_length=20)),
                ('linked_test_result_id', models.CharField(help_text='Reference to mcmi4-signal TestResult ID', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('consultant_user', models.ForeignKey(help_text='User completing the reflection (consultant)', on_delete=django.db.models.deletion.PROTECT, related_name='reflection_workspaces', to=settings.AUTH_USER_MODEL)),
                ('workspace_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='swm_mcmi4_reflection.workspacedefinition')),
            ],
            options={
                'verbose_name': 'Reflection Workspace Instance',
                'verbose_name_plural': 'Reflection Workspace Instances',
                'db_table': 'reflection_workspace_instances',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Action: created, updated, sealed', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reflection_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='swm_mcmi4_reflection.workspaceinstance')),
            ],
            options={
                'verbose_name': 'Reflection Workspace Audit Log',
                'verbose_name_plural': 'Reflection Workspace Audit Logs',
                'db_table': 'reflection_workspace_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('reflection:v1', 'Reflection v1')], default='reflection:v1', max_length=50)),
                ('content', models.JSONField(help_text='Reflection answers and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sealed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reflection_artifacts_created', to=settings.AUTH_USER_MODEL)),
                ('workspace_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='swm_mcmi4_reflection.workspaceinstance')),
            ],
            options={
                'verbose_name': 'Reflection Workspace Artifact',
                'verbose_name_plural': 'Reflection Workspace Artifacts',
                'db_table': 'reflection_workspace_artifacts',
            },
        ),
        migrations.AddIndex(
            model_name='workspaceinstance',
            index=models.Index(fields=['consultant_user', '-created_at'], name='reflection__consult_758ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinstance',
            index=models.Index(fields=['linked_test_result_id'], name='reflection__linked__04d68d_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspaceinstance',
            constraint=models.UniqueConstraint(fields=('consultant_user', 'linked_test_result_id'), name='unique_reflection_per_consultant_signal'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['workspace_instance', '-timestamp'], name='reflection__workspa_715ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='reflection__user_id_887ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceartifact',
            index=models.Index(fields=['workspace_instance', 'artifact_type'], name='reflection__workspa_d6f992_idx'),
        ),
    ]
