# Generated by Django 5.2.9 on 2026-01-30 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0086_extend_interpretation_type_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterpretation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('interpreter_type', models.CharField(max_length=50)),
                ('narrative', models.JSONField()),
                ('suggested_diagnoses', models.JSONField(default=list)),
                ('therapeutic_route', models.JSONField()),
                ('model_used', models.CharField(default='gpt-4-turbo-preview', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('rag_sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_cached', models.BooleanField(default=False)),
                ('cache_hit_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interpretations', to='api.testresult')),
            ],
            options={
                'db_table': 'ai_interpretations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=50)),
                ('test_type', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('latency_ms', models.IntegerField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interpretation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_engine.aiinterpretation')),
            ],
            options={
                'db_table': 'ai_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='aiinterpretation',
            index=models.Index(fields=['test_result', '-created_at'], name='ai_interpre_test_re_5db231_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinterpretation',
            index=models.Index(fields=['patient', '-created_at'], name='ai_interpre_patient_dc76b1_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinterpretation',
            index=models.Index(fields=['interpreter_type'], name='ai_interpre_interpr_e49256_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='ai_audit_lo_user_id_1c7128_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['test_type', '-timestamp'], name='ai_audit_lo_test_ty_fd13b6_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['success'], name='ai_audit_lo_success_236a92_idx'),
        ),
    ]
