# Generated by Django 5.2.9 on 2026-01-24 23:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabalaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('method_id', models.CharField(choices=[('numerologia', 'Numerología Cabalística'), ('tarot', 'Correspondencias Tarot'), ('astrologia', 'Correspondencias Astrológicas'), ('gematria', 'Gematría'), ('meditacion', 'Meditación Guiada'), ('bioemotional', 'Biodescodificación'), ('libre', 'Exploración Libre')], default='libre', help_text='Método de exploración utilizado', max_length=50)),
                ('status', models.CharField(choices=[('created', 'Creada'), ('in_progress', 'En Progreso'), ('paused', 'Pausada'), ('closed', 'Cerrada'), ('archived', 'Archivada')], default='created', max_length=20)),
                ('tree_state', models.JSONField(blank=True, default=dict, help_text='Estado estructural del Árbol de la Vida (TreeStructuralState)')),
                ('session_notes', models.TextField(blank=True, default='')),
                ('clinical_context', models.JSONField(blank=True, default=dict, help_text='Contexto clínico opcional (bioemotional, tests, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(help_text='Usuario/paciente siendo explorado', on_delete=django.db.models.deletion.PROTECT, related_name='cabala_sessions_as_patient', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(help_text='Terapeuta que conduce la sesión', on_delete=django.db.models.deletion.PROTECT, related_name='cabala_sessions_as_therapist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Cábala',
                'verbose_name_plural': 'Sesiones de Cábala',
                'db_table': 'swm_cabala_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CabalaSessionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tree_state', models.JSONField(default=dict, help_text='Estado del árbol en este momento')),
                ('notes', models.TextField(blank=True, default='', help_text='Notas del terapeuta en este momento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='swm_cabala.cabalasession')),
            ],
            options={
                'verbose_name': 'Snapshot de Sesión Cábala',
                'verbose_name_plural': 'Snapshots de Sesiones Cábala',
                'db_table': 'swm_cabala_session_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PathObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_index', models.IntegerField(choices=[(0, 'Aleph - Keter↔Chokhmah'), (1, 'Beth - Keter↔Binah'), (2, 'Gimel - Keter↔Tiferet'), (3, 'Daleth - Chokhmah↔Binah'), (4, 'Heh - Chokhmah↔Tiferet'), (5, 'Vav - Chokhmah↔Chesed'), (6, 'Zayin - Binah↔Tiferet'), (7, 'Cheth - Binah↔Gevurah'), (8, 'Teth - Chesed↔Gevurah'), (9, 'Yod - Chesed↔Tiferet'), (10, 'Kaph - Chesed↔Netzach'), (11, 'Lamed - Gevurah↔Tiferet'), (12, 'Mem - Gevurah↔Hod'), (13, 'Nun - Tiferet↔Netzach'), (14, 'Samekh - Tiferet↔Yesod'), (15, 'Ayin - Tiferet↔Hod'), (16, 'Peh - Netzach↔Hod'), (17, 'Tzaddi - Netzach↔Yesod'), (18, 'Qoph - Netzach↔Malkhut'), (19, 'Resh - Hod↔Yesod'), (20, 'Shin - Hod↔Malkhut'), (21, 'Tav - Yesod↔Malkhut')], help_text='Índice del sendero (0-21, correspondiente a letras hebreas)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('flow_direction', models.CharField(choices=[('ascending', 'Ascendente (hacia Keter)'), ('descending', 'Descendente (hacia Malkhut)'), ('balanced', 'Equilibrado')], default='balanced', help_text='Dirección del flujo energético', max_length=20)),
                ('observation', models.TextField(blank=True, default='', help_text='Observación sobre este sendero')),
                ('is_blocked', models.BooleanField(default=False, help_text='Indica si el sendero está bloqueado')),
                ('is_active', models.BooleanField(default=False, help_text='Indica si el sendero está activamente trabajándose')),
                ('tarot_card', models.CharField(blank=True, default='', help_text='Carta de Tarot correspondiente (si aplica)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_observations', to='swm_cabala.cabalasession')),
            ],
            options={
                'verbose_name': 'Observación de Sendero',
                'verbose_name_plural': 'Observaciones de Senderos',
                'db_table': 'swm_cabala_path_observations',
                'ordering': ['path_index'],
            },
        ),
        migrations.CreateModel(
            name='SefirahObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sefirah_name', models.CharField(choices=[('keter', 'Keter (Corona)'), ('chokhmah', 'Chokhmah (Sabiduría)'), ('binah', 'Binah (Entendimiento)'), ('chesed', 'Chesed (Misericordia)'), ('gevurah', 'Gevurah (Severidad)'), ('tiferet', 'Tiferet (Belleza)'), ('netzach', 'Netzach (Victoria)'), ('hod', 'Hod (Esplendor)'), ('yesod', 'Yesod (Fundamento)'), ('malkhut', 'Malkhut (Reino)'), ('daat', "Da'at (Conocimiento)")], help_text='Sefirah being observed', max_length=20)),
                ('observation', models.TextField(help_text='Observación terapéutica sobre esta sefirah')),
                ('intensity', models.IntegerField(default=5, help_text='Intensidad de la observación (1=leve, 10=muy significativo)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('emotion_type', models.CharField(choices=[('joy', 'Alegría'), ('sadness', 'Tristeza'), ('anger', 'Ira'), ('fear', 'Miedo'), ('love', 'Amor'), ('guilt', 'Culpa'), ('shame', 'Vergüenza'), ('peace', 'Paz'), ('anxiety', 'Ansiedad'), ('grief', 'Duelo'), ('hope', 'Esperanza'), ('despair', 'Desesperanza'), ('other', 'Otro')], default='other', help_text='Tipo de emoción asociada', max_length=20)),
                ('is_blocked', models.BooleanField(default=False, help_text='Indica si la sefirah está bloqueada')),
                ('is_activated', models.BooleanField(default=False, help_text='Indica si la sefirah está activada/iluminada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sefirah_observations', to='swm_cabala.cabalasession')),
            ],
            options={
                'verbose_name': 'Observación de Sefirah',
                'verbose_name_plural': 'Observaciones de Sefirot',
                'db_table': 'swm_cabala_sefirah_observations',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cabalasession',
            index=models.Index(fields=['patient', 'status'], name='swm_cabala__patient_5a6033_idx'),
        ),
        migrations.AddIndex(
            model_name='cabalasession',
            index=models.Index(fields=['therapist', 'status'], name='swm_cabala__therapi_ec619b_idx'),
        ),
        migrations.AddIndex(
            model_name='cabalasession',
            index=models.Index(fields=['created_at'], name='swm_cabala__created_0b3e9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pathobservation',
            unique_together={('session', 'path_index')},
        ),
        migrations.AlterUniqueTogether(
            name='sefirahobservation',
            unique_together={('session', 'sefirah_name')},
        ),
    ]
