# Generated by Django 5.2.9 on 2026-01-31 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_cabala_ai_usage_log'),
        ('swm_cabala', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GematriaReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('pitagoras', 'Pitágoras'), ('gematria-standard', 'Gematría Estándar'), ('gematria-katan', 'Gematría Katan'), ('mispar-gadol', 'Mispar Gadol'), ('mispar-siduri', 'Mispar Siduri'), ('milui', 'Milui'), ('atbash', 'Atbash'), ('albam', 'Albam'), ('avgad', 'Avgad'), ('temurah', 'Temurah'), ('notarikon', 'Notarikón')], help_text='Método gematrico utilizado', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('saved', 'Guardado'), ('reviewed', 'Revisado'), ('synthesized', 'Sintetizado')], default='saved', help_text='Estado de la lectura', max_length=20)),
                ('input_name', models.CharField(help_text='Nombre completo analizado', max_length=200)),
                ('input_birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento utilizada', null=True)),
                ('hebrew_transliteration', models.CharField(blank=True, help_text='Transliteración hebrea del nombre', max_length=200)),
                ('calculated_numbers', models.JSONField(default=dict, help_text='Números calculados: esencia, expresion, herencia, caminoVida, etc.')),
                ('calculation_details', models.JSONField(default=dict, help_text='Detalles del cálculo: palabras, valores, transformaciones')),
                ('sefirotic_correspondence', models.JSONField(default=dict, help_text='Correspondencia sefirótica derivada')),
                ('number_interpretations', models.JSONField(default=dict, help_text='Interpretaciones por número: arquetipo, luz, sombra, etc.')),
                ('method_interpretation', models.TextField(blank=True, help_text='Interpretación general del método para esta lectura')),
                ('therapist_notes', models.TextField(blank=True, help_text='Notas del terapeuta sobre esta lectura')),
                ('therapist_interpretation', models.TextField(blank=True, help_text='Interpretación personalizada del terapeuta')),
                ('highlights', models.JSONField(default=list, help_text='Puntos destacados marcados por el terapeuta')),
                ('ai_interpretation', models.TextField(blank=True, help_text='Interpretación generada por IA (si disponible)')),
                ('ai_generated_at', models.DateTimeField(blank=True, help_text='Cuándo se generó la interpretación IA', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Paciente/consultante analizado', on_delete=django.db.models.deletion.CASCADE, related_name='gematria_readings', to='api.patient')),
                ('therapist', models.ForeignKey(help_text='Terapeuta que ejecutó la lectura', on_delete=django.db.models.deletion.CASCADE, related_name='created_gematria_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura Gematrica',
                'verbose_name_plural': 'Lecturas Gematricas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GematriaSynthesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('generated', 'Generado'), ('reviewed', 'Revisado por Terapeuta'), ('validated', 'Validado'), ('exported', 'Exportado a Síntesis')], default='draft', max_length=20)),
                ('title', models.CharField(default='Síntesis Gematrica', help_text='Título descriptivo de la síntesis', max_length=200)),
                ('ai_synthesis', models.JSONField(default=dict, help_text='Síntesis estructurada generada por IA')),
                ('ai_narrative', models.TextField(blank=True, help_text='Narrativa humanizada de la síntesis')),
                ('cross_swm_sources', models.JSONField(default=list, help_text='Lista de fuentes SWM consultadas: [{swm: "mcmi4", workspace_id: "...", key_findings: [...]}]')),
                ('cross_swm_synthesis', models.JSONField(default=dict, help_text='Síntesis cruzada con otros SWM')),
                ('dominant_numbers', models.JSONField(default=list, help_text='Números dominantes a través de todos los métodos')),
                ('recurring_sefirot', models.JSONField(default=list, help_text='Sefirot recurrentes en los análisis')),
                ('archetypal_patterns', models.JSONField(default=list, help_text='Patrones arquetípicos identificados')),
                ('shadow_themes', models.JSONField(default=list, help_text='Temas de sombra recurrentes')),
                ('light_themes', models.JSONField(default=list, help_text='Fortalezas y luces identificadas')),
                ('tikun_suggestions', models.JSONField(default=list, help_text='Sugerencias de Tikún (rectificación)')),
                ('therapist_validation', models.BooleanField(default=False, help_text='Si el terapeuta ha validado esta síntesis')),
                ('therapist_notes', models.TextField(blank=True, help_text='Notas del terapeuta sobre la síntesis')),
                ('therapist_edits', models.JSONField(default=dict, help_text='Ediciones/correcciones del terapeuta a la síntesis IA')),
                ('exported_to_holistic', models.BooleanField(default=False, help_text='Si se exportó a síntesis holística global')),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('holistic_record_id', models.CharField(blank=True, help_text='ID del AnalysisRecord si se exportó', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Paciente/consultante', on_delete=django.db.models.deletion.CASCADE, related_name='gematria_syntheses', to='api.patient')),
                ('readings', models.ManyToManyField(help_text='Lecturas incluidas en esta síntesis', related_name='syntheses', to='swm_cabala.gematriareading')),
                ('therapist', models.ForeignKey(help_text='Terapeuta que solicitó la síntesis', on_delete=django.db.models.deletion.CASCADE, related_name='created_gematria_syntheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Síntesis Gematrica',
                'verbose_name_plural': 'Síntesis Gematricas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gematriareading',
            index=models.Index(fields=['patient', 'method', '-created_at'], name='swm_cabala__patient_4b1955_idx'),
        ),
        migrations.AddIndex(
            model_name='gematriareading',
            index=models.Index(fields=['therapist', '-created_at'], name='swm_cabala__therapi_9ec738_idx'),
        ),
        migrations.AddIndex(
            model_name='gematriareading',
            index=models.Index(fields=['status', '-created_at'], name='swm_cabala__status_3a681d_idx'),
        ),
        migrations.AddIndex(
            model_name='gematriasynthesis',
            index=models.Index(fields=['patient', '-created_at'], name='swm_cabala__patient_dedfa2_idx'),
        ),
        migrations.AddIndex(
            model_name='gematriasynthesis',
            index=models.Index(fields=['status', '-created_at'], name='swm_cabala__status_f39496_idx'),
        ),
    ]
