# Generated by Django 6.0.6 on 2026-06-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sha', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspaceartifact',
            new_name='swm_sha_wor_workspa_5ae901_idx',
            old_name='swm_sha_wo_workspa_b68541_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceartifact',
            new_name='swm_sha_wor_workspa_d7d61b_idx',
            old_name='swm_sha_wo_workspa_07d45a_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceinstance',
            new_name='swm_sha_wor_definit_c56b8e_idx',
            old_name='swm_sha_wo_definit_7d7491_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceinstance',
            new_name='swm_sha_wor_subject_63bddc_idx',
            old_name='swm_sha_wo_subject_4c1c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceinstance',
            new_name='swm_sha_wor_creator_2e4e1e_idx',
            old_name='swm_sha_wo_creator_19b22b_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacepermission',
            new_name='swm_sha_wor_workspa_05730c_idx',
            old_name='swm_sha_wo_workspa_60cc29_idx',
        ),
    ]
