SYMBOLIC_MEANINGS = {
    "El Loco": {
        "core": "Potencial previo a la forma: impulso inicial y umbral de posibilidad.",
        "keywords": ["potencial", "umbral", "incipiente", "apertura", "origen"],
        "tree": "Fuerza raíz (marco hermético simplificado).",
        "notes": "Marco hermético: se privilegia estructura y fuerza, no consejo.",
    },
    "El Mago": {
        "core": "Voluntad concentrada: dirección, herramienta y acto de conjunción.",
        "keywords": ["voluntad", "foco", "herramienta", "dirección", "acto"],
        "tree": "Operación: forma y canal (simplificado).",
        "notes": "Lectura de fuerzas: acto de organizar símbolos en una intención formal.",
    },
    "La Sacerdotisa": {
        "core": "Velo y receptividad: conocimiento velado y silencio operativo.",
        "keywords": ["velo", "receptividad", "silencio", "reserva", "umbral"],
        "tree": "Eje de recepción (simplificado).",
        "notes": "Hermético: lo velado se preserva como estructura, no como misterio narrativo.",
    },
    "La Emperatriz": {
        "core": "Generación y fertilidad simbólica: expansión de forma y campo.",
        "keywords": ["generación", "campo", "crecimiento", "abundancia", "forma"],
        "tree": "Expansión de la forma (simplificado).",
        "notes": "Se lee como potencia creadora y orden de crecimiento, no como promesa.",
    },
    "El Emperador": {
        "core": "Estructura y ley: delimitación, marco y sostén de orden.",
        "keywords": ["estructura", "ley", "límite", "sostén", "orden"],
        "tree": "Marco de estabilización (simplificado).",
        "notes": "El énfasis es estructural: límites como forma, no como imposición.",
    },
    "El Hierofante": {
        "core": "Transmisión de forma: tradición como sistema de símbolos y reglas.",
        "keywords": ["tradición", "transmisión", "símbolo", "regla", "forma"],
        "tree": "Puente de transmisión (simplificado).",
        "notes": "Hermético: tradición entendida como lenguaje y estructura.",
    },
    "Los Enamorados": {
        "core": "Alianza y elección: unión de polos para producir coherencia.",
        "keywords": ["alianza", "elección", "unión", "coherencia", "polaridad"],
        "tree": "Conjunción de polos (simplificado).",
        "notes": "No se prescribe; se describe la operación de vínculo entre fuerzas.",
    },
    "El Carro": {
        "core": "Conducción: dirección sostenida por disciplina y vector de avance.",
        "keywords": ["conducción", "vector", "avance", "disciplina", "dirección"],
        "tree": "Vector de realización (simplificado).",
        "notes": "Se enfatiza dirección como estructura, no como triunfo.",
    },
    "La Justicia": {
        "core": "Equilibrio de ley: ajuste de forma para mantener proporción.",
        "keywords": ["equilibrio", "ajuste", "proporción", "ley", "medida"],
        "tree": "Ajuste de estructura (simplificado).",
        "notes": "Hermético: ajuste como operación formal; no es juicio moral.",
    },
    "El Ermitaño": {
        "core": "Concentración: retiro para refinar el símbolo y la medida interna.",
        "keywords": ["retiro", "refinamiento", "luz", "medida", "concentración"],
        "tree": "Purificación de enfoque (simplificado).",
        "notes": "Se lee como proceso de concentración, no como aislamiento prescrito.",
    },
    "La Rueda de la Fortuna": {
        "core": "Ciclo y giro: movimiento de fases dentro de una estructura mayor.",
        "keywords": ["ciclo", "giro", "fase", "cambio", "estructura"],
        "tree": "Rotación de fases (simplificado).",
        "notes": "Hermético: la rueda es estructura de cambio, no destino literal.",
    },
    "La Fuerza": {
        "core": "Dominio sereno: potencia contenida y dirección sin ruptura.",
        "keywords": ["potencia", "contención", "serenidad", "dirección", "dominio"],
        "tree": "Potencia contenida (simplificado).",
        "notes": "Fuerza como forma estable, no como agresión.",
    },
    "El Colgado": {
        "core": "Inversión de perspectiva: suspensión para reordenar el símbolo.",
        "keywords": ["suspensión", "inversión", "perspectiva", "reorden", "pausa"],
        "tree": "Pausa estructural (simplificado).",
        "notes": "Se describe la suspensión como operación de re-encuadre.",
    },
    "La Muerte": {
        "core": "Corte de forma: transición y cierre de un ciclo estructural.",
        "keywords": ["corte", "transición", "cierre", "umbral", "relevo"],
        "tree": "Cambio de forma (simplificado).",
        "notes": "No predice; señala cambio de estructura.",
    },
    "La Templanza": {
        "core": "Alquimia mínima: mezcla y ajuste para estabilizar una nueva medida.",
        "keywords": ["mezcla", "alquimia", "ajuste", "síntesis", "equilibrio"],
        "tree": "Síntesis de corrientes (simplificado).",
        "notes": "Hermético: síntesis como operación formal.",
    },
    "El Diablo": {
        "core": "Atadura de forma: fijación y densidad de deseo/imagen en estructura.",
        "keywords": ["atadura", "fijación", "densidad", "imagen", "vínculo"],
        "tree": "Fijación de forma (simplificado).",
        "notes": "Se describe atadura simbólica, no se moraliza.",
    },
    "La Torre": {
        "core": "Ruptura estructural: caída de una forma para revelar lo esencial.",
        "keywords": ["ruptura", "caída", "revelación", "fractura", "liberación"],
        "tree": "Descarga de estructura (simplificado).",
        "notes": "No es advertencia; es descripción de colapso de forma.",
    },
    "La Estrella": {
        "core": "Claridad y orientación: señal estable tras el quiebre.",
        "keywords": ["claridad", "orientación", "señal", "apertura", "flujo"],
        "tree": "Orientación de forma (simplificado).",
        "notes": "Se lee como señal y orientación simbólica.",
    },
    "La Luna": {
        "core": "Umbral de lo velado: reflejo, niebla y tránsito por símbolos indirectos.",
        "keywords": ["reflejo", "niebla", "umbral", "indirecto", "marea"],
        "tree": "Tránsito por lo velado (simplificado).",
        "notes": "Hermético: se describe lo velado como dinámica de símbolos.",
    },
    "El Sol": {
        "core": "Manifestación: claridad, coherencia y presencia de forma visible.",
        "keywords": ["claridad", "presencia", "coherencia", "manifestación", "luz"],
        "tree": "Consolidación de forma (simplificado).",
        "notes": "No promete; describe claridad como estado de forma.",
    },
    "El Juicio": {
        "core": "Llamado de forma: reorden y respuesta a un patrón mayor.",
        "keywords": ["llamado", "reorden", "respuesta", "patrón", "umbral"],
        "tree": "Reconfiguración (simplificado).",
        "notes": "Hermético: reorden como evento de estructura.",
    },
    "El Mundo": {
        "core": "Cierre completo: integración y totalidad de un ciclo formal.",
        "keywords": ["integración", "totalidad", "cierre", "síntesis", "forma"],
        "tree": "Totalización (simplificado).",
        "notes": "Se describe completitud estructural, no resultado prescrito.",
    },
}

