SYMBOLIC_MEANINGS = {
    "El Loco": {
        "core": "Potencial sin forma: inicio no dirigido y movimiento abierto.",
        "keywords": ["apertura", "camino", "impulso", "umbral", "libertad"],
        "tree": "",
        "notes": "Marsella prioriza arquetipo visual y gesto, no esoterismo técnico.",
    },
    "El Mago": {
        "core": "Mesa de herramientas: comienzo de acción y habilidad disponible.",
        "keywords": ["herramientas", "inicio", "destreza", "gesto", "presencia"],
        "tree": "",
        "notes": "Lectura simple: lo disponible y lo que se organiza en la escena.",
    },
    "La Sacerdotisa": {
        "core": "Libro interior: reserva, umbral y conocimiento guardado.",
        "keywords": ["reserva", "libro", "umbral", "silencio", "custodia"],
        "tree": "",
        "notes": "Se describe la pausa y el umbral, sin prometer revelaciones.",
    },
    "La Emperatriz": {
        "core": "Expansión de vida: expresión y fertilidad de forma.",
        "keywords": ["expansión", "vida", "expresión", "forma", "crecimiento"],
        "tree": "",
        "notes": "Arquetipo de expansión y expresión, no resultado.",
    },
    "El Emperador": {
        "core": "Asiento de orden: estructura, límites y sostén.",
        "keywords": ["orden", "límite", "estructura", "sostén", "marco"],
        "tree": "",
        "notes": "Se enfatiza el marco que sostiene, no control psicológico.",
    },
    "El Hierofante": {
        "core": "Puente de tradición: norma compartida y transmisión.",
        "keywords": ["tradición", "norma", "transmisión", "puente", "símbolo"],
        "tree": "",
        "notes": "Marsella: tradición como forma visible y regla social de símbolos.",
    },
    "Los Enamorados": {
        "core": "Elección visible: vínculo y cruce de caminos.",
        "keywords": ["elección", "vínculo", "cruce", "polaridad", "alianza"],
        "tree": "",
        "notes": "Arquetipo de elección y vínculo, sin prescripción.",
    },
    "El Carro": {
        "core": "Movimiento conducido: avance por dirección y forma.",
        "keywords": ["avance", "dirección", "conducción", "movimiento", "forma"],
        "tree": "",
        "notes": "Lectura visual: conducción y avance como escena.",
    },
    "La Justicia": {
        "core": "Balanza y espada: medida y ajuste de la escena.",
        "keywords": ["medida", "ajuste", "equilibrio", "forma", "orden"],
        "tree": "",
        "notes": "No es juicio moral: es medida y ajuste simbólico.",
    },
    "El Ermitaño": {
        "core": "Luz mínima: retirada para ver con claridad la medida.",
        "keywords": ["luz", "retirada", "claridad", "medida", "paso"],
        "tree": "",
        "notes": "Arquetipo de paso lento y foco, sin consejo.",
    },
    "La Rueda de la Fortuna": {
        "core": "Cambio de fase: giro y alternancia en el ciclo.",
        "keywords": ["giro", "fase", "cambio", "ciclo", "alternancia"],
        "tree": "",
        "notes": "Describe movimiento de ciclo; no promete resultados.",
    },
    "La Fuerza": {
        "core": "Dominio sereno: potencia contenida y gesto firme.",
        "keywords": ["potencia", "contención", "gesto", "firmeza", "calma"],
        "tree": "",
        "notes": "Fuerza como gesto estable, no violencia.",
    },
    "El Colgado": {
        "core": "Pausa invertida: suspensión y cambio de perspectiva.",
        "keywords": ["pausa", "suspensión", "inversión", "perspectiva", "umbral"],
        "tree": "",
        "notes": "Marsella: el gesto invierte la escena para leer distinto.",
    },
    "La Muerte": {
        "core": "Corte y transición: fin de forma y paso a otra.",
        "keywords": ["corte", "transición", "fin", "umbral", "cambio"],
        "tree": "",
        "notes": "Describe transición; no predicción.",
    },
    "La Templanza": {
        "core": "Mezcla y ajuste: flujo entre recipientes y equilibrio de medida.",
        "keywords": ["mezcla", "flujo", "ajuste", "equilibrio", "medida"],
        "tree": "",
        "notes": "Arquetipo de mezcla y equilibrio visible.",
    },
    "El Diablo": {
        "core": "Atadura y deseo: fijación de imagen y cadena simbólica.",
        "keywords": ["atadura", "cadena", "imagen", "deseo", "fijación"],
        "tree": "",
        "notes": "Se describe atadura simbólica sin moralizar.",
    },
    "La Torre": {
        "core": "Caída de forma: ruptura y liberación de lo que estaba fijado.",
        "keywords": ["ruptura", "caída", "liberación", "fractura", "impacto"],
        "tree": "",
        "notes": "Evento de ruptura de forma, no advertencia técnica.",
    },
    "La Estrella": {
        "core": "Señal clara: orientación y apertura tras el cambio.",
        "keywords": ["señal", "orientación", "apertura", "flujo", "claridad"],
        "tree": "",
        "notes": "Arquetipo de señal y apertura, sin promesa.",
    },
    "La Luna": {
        "core": "Reflejo y tránsito: lo indirecto y lo velado como paisaje.",
        "keywords": ["reflejo", "velado", "indirecto", "paisaje", "umbral"],
        "tree": "",
        "notes": "Marsella lee lo velado como escena, no como secreto clínico.",
    },
    "El Sol": {
        "core": "Claridad presente: forma visible y coherencia del día.",
        "keywords": ["claridad", "día", "coherencia", "presencia", "luz"],
        "tree": "",
        "notes": "Describe claridad como escena abierta.",
    },
    "El Juicio": {
        "core": "Llamado y respuesta: reorden visible y despertar de forma.",
        "keywords": ["llamado", "respuesta", "reorden", "despertar", "umbral"],
        "tree": "",
        "notes": "Arquetipo de llamado; no sentencia.",
    },
    "El Mundo": {
        "core": "Cierre integrado: totalidad del ciclo y danza de forma completa.",
        "keywords": ["totalidad", "cierre", "integración", "ciclo", "forma"],
        "tree": "",
        "notes": "Describe completitud simbólica, sin prometer logro.",
    },
}

