SYMBOLIC_MEANINGS = {
    "El Loco": {
        "core": "Símbolo abierto: inicio sin ruta fija, umbral de exploración.",
        "keywords": ["inicio", "umbral", "apertura", "exploración", "posibilidad"],
        "tree": "",
        "notes": "Oráculo simbólico: lectura libre, no jerárquica, estructurada por palabras clave.",
    },
    "El Mago": {
        "core": "Símbolo de agencia: reunir elementos y darles forma visible.",
        "keywords": ["agencia", "elementos", "forma", "acto", "conexión"],
        "tree": "",
        "notes": "Oráculo: se describe operación simbólica sin prescripción.",
    },
    "La Sacerdotisa": {
        "core": "Símbolo de reserva: guardar, observar y mantener umbral.",
        "keywords": ["reserva", "observación", "umbral", "silencio", "custodia"],
        "tree": "",
        "notes": "Oráculo: el valor está en el umbral y la contención.",
    },
    "La Emperatriz": {
        "core": "Símbolo de crecimiento: expansión y fertilidad de forma.",
        "keywords": ["crecimiento", "expansión", "fertilidad", "forma", "campo"],
        "tree": "",
        "notes": "Oráculo: crecimiento como dinámica de forma.",
    },
    "El Emperador": {
        "core": "Símbolo de marco: límites y estructura que sostienen.",
        "keywords": ["marco", "límite", "estructura", "sostén", "orden"],
        "tree": "",
        "notes": "Oráculo: marco como forma, no mandato.",
    },
    "El Hierofante": {
        "core": "Símbolo de transmisión: norma compartida y lenguaje de forma.",
        "keywords": ["transmisión", "lenguaje", "norma", "forma", "tradición"],
        "tree": "",
        "notes": "Oráculo: tradición como lenguaje de símbolos.",
    },
    "Los Enamorados": {
        "core": "Símbolo de vínculo: elección y alineación entre polos.",
        "keywords": ["vínculo", "elección", "alineación", "polaridad", "cruce"],
        "tree": "",
        "notes": "Oráculo: vínculo como cruce de caminos simbólico.",
    },
    "El Carro": {
        "core": "Símbolo de dirección: avance y conducción de forma.",
        "keywords": ["dirección", "avance", "conducción", "rumbo", "vector"],
        "tree": "",
        "notes": "Oráculo: dirección como vector simbólico.",
    },
    "La Justicia": {
        "core": "Símbolo de medida: equilibrio y ajuste de proporción.",
        "keywords": ["medida", "equilibrio", "ajuste", "proporción", "orden"],
        "tree": "",
        "notes": "Oráculo: medida como forma, no moral.",
    },
    "El Ermitaño": {
        "core": "Símbolo de foco: retirada para ver con claridad.",
        "keywords": ["foco", "retirada", "claridad", "luz", "paso"],
        "tree": "",
        "notes": "Oráculo: foco como luz mínima.",
    },
    "La Rueda de la Fortuna": {
        "core": "Símbolo de ciclo: giro y alternancia de fases.",
        "keywords": ["ciclo", "giro", "fase", "alternancia", "cambio"],
        "tree": "",
        "notes": "Oráculo: ciclo como dinámica, no destino.",
    },
    "La Fuerza": {
        "core": "Símbolo de contención: potencia serena y forma estable.",
        "keywords": ["contención", "potencia", "serenidad", "forma", "dominio"],
        "tree": "",
        "notes": "Oráculo: potencia contenida como forma.",
    },
    "El Colgado": {
        "core": "Símbolo de pausa: inversión y perspectiva nueva.",
        "keywords": ["pausa", "inversión", "perspectiva", "umbral", "reorden"],
        "tree": "",
        "notes": "Oráculo: pausa como cambio de mirada.",
    },
    "La Muerte": {
        "core": "Símbolo de transición: cierre de forma y paso a otra.",
        "keywords": ["transición", "cierre", "corte", "umbral", "cambio"],
        "tree": "",
        "notes": "Oráculo: transición como cambio de fase simbólico.",
    },
    "La Templanza": {
        "core": "Símbolo de mezcla: equilibrar corrientes para estabilizar.",
        "keywords": ["mezcla", "equilibrio", "corriente", "estabilidad", "medida"],
        "tree": "",
        "notes": "Oráculo: mezcla como operación simbólica.",
    },
    "El Diablo": {
        "core": "Símbolo de atadura: fijación de imagen y cadena de forma.",
        "keywords": ["atadura", "fijación", "imagen", "cadena", "densidad"],
        "tree": "",
        "notes": "Oráculo: atadura simbólica sin moralizar.",
    },
    "La Torre": {
        "core": "Símbolo de ruptura: caída de forma rígida y liberación.",
        "keywords": ["ruptura", "caída", "liberación", "fractura", "impacto"],
        "tree": "",
        "notes": "Oráculo: ruptura como evento de forma.",
    },
    "La Estrella": {
        "core": "Símbolo de orientación: señal clara y apertura.",
        "keywords": ["orientación", "señal", "apertura", "claridad", "flujo"],
        "tree": "",
        "notes": "Oráculo: orientación como señal, no promesa.",
    },
    "La Luna": {
        "core": "Símbolo de reflejo: tránsito por lo indirecto y lo velado.",
        "keywords": ["reflejo", "indirecto", "velado", "tránsito", "umbral"],
        "tree": "",
        "notes": "Oráculo: reflejo como paisaje simbólico.",
    },
    "El Sol": {
        "core": "Símbolo de claridad: presencia visible y coherencia.",
        "keywords": ["claridad", "presencia", "coherencia", "luz", "día"],
        "tree": "",
        "notes": "Oráculo: claridad como forma visible.",
    },
    "El Juicio": {
        "core": "Símbolo de llamado: reorden y cambio de nivel.",
        "keywords": ["llamado", "reorden", "umbral", "respuesta", "despertar"],
        "tree": "",
        "notes": "Oráculo: llamado como cambio de escena.",
    },
    "El Mundo": {
        "core": "Símbolo de totalidad: integración y cierre de ciclo.",
        "keywords": ["totalidad", "integración", "cierre", "ciclo", "síntesis"],
        "tree": "",
        "notes": "Oráculo: totalidad como forma integrada.",
    },
}

