SYMBOLIC_MEANINGS = {
    "El Loco": {
        "core": "Inicio del viaje: impulso, confianza y apertura a lo nuevo.",
        "keywords": ["viaje", "apertura", "inicio", "salto", "posibilidad"],
        "tree": "",
        "notes": "Rider–Waite enfatiza imagen narrativa y escena simbólica moderna.",
    },
    "El Mago": {
        "core": "Puente entre cielo y tierra: dirigir recursos hacia una forma concreta.",
        "keywords": ["dirección", "recursos", "puente", "acto", "foco"],
        "tree": "",
        "notes": "Narrativo: la mesa ordena símbolos para una forma visible.",
    },
    "La Sacerdotisa": {
        "core": "Velo y silencio: aquello que se guarda y se observa sin exponer.",
        "keywords": ["velo", "silencio", "observación", "umbral", "reserva"],
        "tree": "",
        "notes": "Se describe lo velado como escena, sin prometer revelación.",
    },
    "La Emperatriz": {
        "core": "Crecimiento visible: fertilidad de campo y expansión de forma.",
        "keywords": ["crecimiento", "campo", "abundancia", "expansión", "vida"],
        "tree": "",
        "notes": "Narrativa de crecimiento: la forma se vuelve generativa.",
    },
    "El Emperador": {
        "core": "Trono y marco: estructura, límites y dirección estable.",
        "keywords": ["marco", "estructura", "límite", "estabilidad", "dirección"],
        "tree": "",
        "notes": "Se lee como marco de orden, no como mandato psicológico.",
    },
    "El Hierofante": {
        "core": "Puente de tradición: lenguaje compartido y forma transmitida.",
        "keywords": ["tradición", "lenguaje", "transmisión", "forma", "norma"],
        "tree": "",
        "notes": "Rider–Waite: tradición como escena de transmisión simbólica.",
    },
    "Los Enamorados": {
        "core": "Elección con vínculo: alineación de valores y cruce de caminos.",
        "keywords": ["elección", "vínculo", "alineación", "valores", "cruce"],
        "tree": "",
        "notes": "Narrativo: decisión como escena de unión y dirección.",
    },
    "El Carro": {
        "core": "Avance dirigido: sostener rumbo en medio de fuerzas opuestas.",
        "keywords": ["avance", "rumbo", "dirección", "fuerzas", "conducción"],
        "tree": "",
        "notes": "Se describe el rumbo, sin prescribir victoria.",
    },
    "La Justicia": {
        "core": "Balanza y medida: ajuste de forma para recuperar proporción.",
        "keywords": ["medida", "proporción", "ajuste", "equilibrio", "orden"],
        "tree": "",
        "notes": "No es moral: es medida y proporción simbólica.",
    },
    "El Ermitaño": {
        "core": "Lámpara en la noche: claridad buscada en retirada y foco.",
        "keywords": ["lámpara", "foco", "retirada", "claridad", "búsqueda"],
        "tree": "",
        "notes": "Narrativo: la luz guía el paso lento del camino.",
    },
    "La Rueda de la Fortuna": {
        "core": "Giro de ciclo: alternancia de fases y cambio de posición.",
        "keywords": ["ciclo", "giro", "fase", "cambio", "alternancia"],
        "tree": "",
        "notes": "Describe alternancia de fase, no destino literal.",
    },
    "La Fuerza": {
        "core": "Serenidad que contiene: dominar sin romper, orientar sin forzar.",
        "keywords": ["serenidad", "contención", "orientación", "potencia", "calma"],
        "tree": "",
        "notes": "Se lee como contención estable, no como agresión.",
    },
    "El Colgado": {
        "core": "Pausa invertida: ver distinto para reordenar la escena.",
        "keywords": ["pausa", "inversión", "perspectiva", "reorden", "umbral"],
        "tree": "",
        "notes": "Narrativo: el cambio de mirada produce nueva lectura.",
    },
    "La Muerte": {
        "core": "Final de forma: cierre de ciclo y transición a otra escena.",
        "keywords": ["cierre", "transición", "ciclo", "corte", "umbral"],
        "tree": "",
        "notes": "Describe transición estructural, sin predicción.",
    },
    "La Templanza": {
        "core": "Mezcla equilibrada: integrar corrientes para una nueva medida.",
        "keywords": ["mezcla", "integración", "equilibrio", "flujo", "medida"],
        "tree": "",
        "notes": "Narrativo: integrar corrientes en una forma estable.",
    },
    "El Diablo": {
        "core": "Atadura de imagen: vínculo que fija y densifica la escena.",
        "keywords": ["atadura", "imagen", "densidad", "vínculo", "fijación"],
        "tree": "",
        "notes": "Se describe fijación simbólica, no se moraliza.",
    },
    "La Torre": {
        "core": "Ruptura súbita: caída de una forma rígida y liberación de energía.",
        "keywords": ["ruptura", "caída", "liberación", "impacto", "fractura"],
        "tree": "",
        "notes": "Evento de quiebre de forma, sin advertencia técnica.",
    },
    "La Estrella": {
        "core": "Orientación tranquila: señal clara y apertura tras el quiebre.",
        "keywords": ["señal", "orientación", "apertura", "claridad", "flujo"],
        "tree": "",
        "notes": "Narrativo: la señal ordena el camino sin prometer resultado.",
    },
    "La Luna": {
        "core": "Paisaje de reflejos: tránsito por lo indirecto y lo velado.",
        "keywords": ["reflejo", "velado", "tránsito", "indirecto", "umbral"],
        "tree": "",
        "notes": "Describe paisaje simbólico, sin diagnóstico.",
    },
    "El Sol": {
        "core": "Claridad de día: presencia visible y coherencia de forma.",
        "keywords": ["claridad", "presencia", "coherencia", "día", "luz"],
        "tree": "",
        "notes": "Claridad como escena abierta, no promesa.",
    },
    "El Juicio": {
        "core": "Llamado y respuesta: reorden de vida y cambio de nivel de escena.",
        "keywords": ["llamado", "respuesta", "reorden", "umbral", "despertar"],
        "tree": "",
        "notes": "Se describe reorden, sin sentencia moral.",
    },
    "El Mundo": {
        "core": "Cierre completo: integración y totalidad del ciclo vivido.",
        "keywords": ["totalidad", "integración", "cierre", "ciclo", "síntesis"],
        "tree": "",
        "notes": "Totalidad como forma integrada, no logro prescrito.",
    },
}

