SYMBOLIC_MEANINGS = {
    "El Loco": {
        "core": "Umbral de giro: potencia previa a la estructura, movimiento sin eje fijado.",
        "keywords": ["umbral", "potencia", "giro", "apertura", "inicio"],
        "tree": "Síntesis hermética (simplificada).",
        "notes": "R.O.T.A. se expresa como síntesis: ciclos y operaciones.",
    },
    "El Mago": {
        "core": "Operación y vector: herramienta que inicia una secuencia de forma.",
        "keywords": ["operación", "vector", "herramienta", "inicio", "secuencia"],
        "tree": "Operación mínima (simplificada).",
        "notes": "Se describe una operación simbólica, no un consejo de acción.",
    },
    "La Sacerdotisa": {
        "core": "Reservorio: pausa que contiene la fórmula antes del despliegue.",
        "keywords": ["reservorio", "pausa", "fórmula", "velo", "contención"],
        "tree": "Contención de fórmula (simplificada).",
        "notes": "R.O.T.A. lee reserva como contención de operación.",
    },
    "La Emperatriz": {
        "core": "Expansión de campo: la forma se multiplica y se hace visible.",
        "keywords": ["campo", "expansión", "multiplicación", "forma", "flujo"],
        "tree": "Expansión (simplificada).",
        "notes": "No se promete; se describe expansión como fase.",
    },
    "El Emperador": {
        "core": "Fijación de eje: la forma se estabiliza en un marco definido.",
        "keywords": ["eje", "marco", "estabilidad", "fijación", "orden"],
        "tree": "Estabilización (simplificada).",
        "notes": "Eje como estructura, no dominio personal.",
    },
    "El Hierofante": {
        "core": "Regla de transmisión: el símbolo se vuelve norma y rito.",
        "keywords": ["regla", "norma", "rito", "transmisión", "símbolo"],
        "tree": "Transmisión (simplificada).",
        "notes": "R.O.T.A.: rito como estructura repetible.",
    },
    "Los Enamorados": {
        "core": "Conjunción: dos corrientes se alinean para producir coherencia.",
        "keywords": ["conjunción", "corriente", "alineación", "elección", "vínculo"],
        "tree": "Conjunción (simplificada).",
        "notes": "Se describe alineación de corrientes, sin prescripción.",
    },
    "El Carro": {
        "core": "Dirección sostenida: avance con vector y contención.",
        "keywords": ["dirección", "avance", "vector", "contención", "ritmo"],
        "tree": "Vector de avance (simplificado).",
        "notes": "Dirección como ritmo y forma.",
    },
    "La Justicia": {
        "core": "Ajuste de balanza: medida que corrige desviación de la forma.",
        "keywords": ["ajuste", "medida", "corrección", "equilibrio", "forma"],
        "tree": "Corrección (simplificada).",
        "notes": "No moraliza: ajusta estructura.",
    },
    "El Ermitaño": {
        "core": "Refinamiento: foco reducido para concentrar la operación.",
        "keywords": ["refinamiento", "foco", "concentración", "luz", "pausa"],
        "tree": "Concentración (simplificada).",
        "notes": "Se lee como concentración de operación.",
    },
    "La Rueda de la Fortuna": {
        "core": "Giro de ciclo: rotación que reordena posiciones del patrón.",
        "keywords": ["giro", "ciclo", "rotación", "patrón", "fase"],
        "tree": "Ciclo (simplificado).",
        "notes": "R.O.T.A.: giro como mecanismo del patrón.",
    },
    "La Fuerza": {
        "core": "Potencia contenida: intensidad gobernada por forma.",
        "keywords": ["potencia", "intensidad", "forma", "gobierno", "serenidad"],
        "tree": "Contención (simplificada).",
        "notes": "Potencia como forma gobernada.",
    },
    "El Colgado": {
        "core": "Suspensión: inversión de relación para reordenar el patrón.",
        "keywords": ["suspensión", "inversión", "reorden", "pausa", "relación"],
        "tree": "Inversión (simplificada).",
        "notes": "Se describe reorden por inversión.",
    },
    "La Muerte": {
        "core": "Corte de ciclo: cierre de forma y transición hacia otra fase.",
        "keywords": ["corte", "ciclo", "cierre", "transición", "fase"],
        "tree": "Transición (simplificada).",
        "notes": "Cambio de fase, no predicción.",
    },
    "La Templanza": {
        "core": "Síntesis: mezcla controlada para estabilizar una nueva medida.",
        "keywords": ["síntesis", "mezcla", "control", "medida", "equilibrio"],
        "tree": "Síntesis (simplificada).",
        "notes": "R.O.T.A.: mezcla como operación formal.",
    },
    "El Diablo": {
        "core": "Fijación: cadena de imagen/deseo que densifica la estructura.",
        "keywords": ["fijación", "cadena", "imagen", "densidad", "vínculo"],
        "tree": "Densidad (simplificada).",
        "notes": "Describe densidad de vínculo, sin moralizar.",
    },
    "La Torre": {
        "core": "Ruptura de eje: descarga que colapsa una forma rígida.",
        "keywords": ["ruptura", "descarga", "colapso", "eje", "liberación"],
        "tree": "Descarga (simplificada).",
        "notes": "Ruptura como descarga de estructura.",
    },
    "La Estrella": {
        "core": "Señal estable: orientación y recomposición tras la descarga.",
        "keywords": ["señal", "orientación", "recomposición", "flujo", "claridad"],
        "tree": "Orientación (simplificada).",
        "notes": "Se describe orientación como señal.",
    },
    "La Luna": {
        "core": "Tránsito indirecto: reflejos y umbrales dentro del ciclo.",
        "keywords": ["tránsito", "indirecto", "reflejo", "umbral", "marea"],
        "tree": "Umbral (simplificado).",
        "notes": "R.O.T.A.: lo velado como dinámica de ciclo.",
    },
    "El Sol": {
        "core": "Claridad de forma: fase de visibilidad y coherencia.",
        "keywords": ["claridad", "visibilidad", "coherencia", "fase", "presencia"],
        "tree": "Consolidación (simplificada).",
        "notes": "Describe coherencia, no promesa.",
    },
    "El Juicio": {
        "core": "Re-llamado: reorganización del patrón por señal mayor.",
        "keywords": ["reorden", "señal", "llamado", "patrón", "umbral"],
        "tree": "Reconfiguración (simplificada).",
        "notes": "R.O.T.A.: reorganización del patrón.",
    },
    "El Mundo": {
        "core": "Totalización: cierre de ciclo y síntesis completa de forma.",
        "keywords": ["totalidad", "cierre", "síntesis", "ciclo", "forma"],
        "tree": "Totalización (simplificada).",
        "notes": "Cierre de ciclo, sin prescribir logro.",
    },
}

