SYMBOLIC_MEANINGS = {
    "El Loco": {
        "core": "Potencial previo a la emanación: apertura antes de la forma fijada.",
        "keywords": ["potencial", "emanación", "apertura", "origen", "umbral"],
        "tree": "Kéter (simplificado): posibilidad previa a estructura.",
        "notes": "Asignación cabalística simplificada (mock) para lectura estructural.",
    },
    "El Mago": {
        "core": "Canalización de potencia: ordenar símbolos para que la forma emerja.",
        "keywords": ["canal", "orden", "símbolo", "dirección", "forma"],
        "tree": "Jojmá (simplificado): impulso que toma dirección.",
        "notes": "Se expresa como canal/orden de símbolos, no como instrucción.",
    },
    "La Sacerdotisa": {
        "core": "Contención del misterio: reserva que guarda forma antes del despliegue.",
        "keywords": ["contención", "reserva", "velo", "umbral", "custodia"],
        "tree": "Biná (simplificado): matriz y contención de forma.",
        "notes": "Cabalístico: la contención sostiene estructura, no promesa de revelación.",
    },
    "La Emperatriz": {
        "core": "Expansión de forma: el patrón se vuelve fértil y visible.",
        "keywords": ["expansión", "patrón", "fertilidad", "forma", "crecimiento"],
        "tree": "Jesed (simplificado): expansión y apertura del patrón.",
        "notes": "Lectura estructural: expansión como fase, no resultado.",
    },
    "El Emperador": {
        "core": "Delimitación: marco que fija límites y sostiene orden de forma.",
        "keywords": ["marco", "límite", "orden", "estructura", "sostén"],
        "tree": "Guevurá (simplificado): límite y forma contenida.",
        "notes": "Límite como estructura, no mandato personal.",
    },
    "El Hierofante": {
        "core": "Transmisión de símbolo: regla que conecta forma y comunidad.",
        "keywords": ["transmisión", "regla", "símbolo", "puente", "forma"],
        "tree": "Tiferet (simplificado): coherencia y transmisión centrada.",
        "notes": "Cabalístico: transmisión como coherencia de forma.",
    },
    "Los Enamorados": {
        "core": "Conjunción de polos: unión que busca coherencia de sendero.",
        "keywords": ["conjunción", "polaridad", "coherencia", "sendero", "alianza"],
        "tree": "Sendero (simplificado): unión de fuerzas en un eje.",
        "notes": "Se describe conjunción, sin prescripción.",
    },
    "El Carro": {
        "core": "Dirección en el sendero: avance por canal y contención.",
        "keywords": ["dirección", "sendero", "avance", "canal", "contención"],
        "tree": "Netzaj (simplificado): impulso de avance sostenido.",
        "notes": "Cabalístico: avance como canal de energía.",
    },
    "La Justicia": {
        "core": "Ajuste de medida: equilibrar forma para recuperar proporción.",
        "keywords": ["medida", "equilibrio", "ajuste", "proporción", "ley"],
        "tree": "Hod (simplificado): medida y forma regulada.",
        "notes": "Ajuste simbólico, no juicio moral.",
    },
    "El Ermitaño": {
        "core": "Retiro para refinar: foco que concentra la luz del patrón.",
        "keywords": ["retiro", "foco", "refinamiento", "luz", "medida"],
        "tree": "Yesod (simplificado): patrón y canal subyacente.",
        "notes": "Refinar patrón: descripción estructural.",
    },
    "La Rueda de la Fortuna": {
        "core": "Rotación de ciclos: alternancia de estados del patrón.",
        "keywords": ["ciclo", "rotación", "alternancia", "estado", "patrón"],
        "tree": "Ciclos (simplificado): giro dentro del Árbol.",
        "notes": "No destino: rotación estructural.",
    },
    "La Fuerza": {
        "core": "Potencia contenida: energía gobernada por forma y centro.",
        "keywords": ["potencia", "contención", "centro", "forma", "serenidad"],
        "tree": "Tiferet (simplificado): centro que gobierna potencia.",
        "notes": "Potencia contenida, no agresión.",
    },
    "El Colgado": {
        "core": "Suspensión del flujo: invertir mirada para reordenar sendero.",
        "keywords": ["suspensión", "inversión", "reorden", "sendero", "pausa"],
        "tree": "Umbral (simplificado): pausa en el canal.",
        "notes": "Descripción de pausa estructural.",
    },
    "La Muerte": {
        "core": "Corte de forma: transición y cambio de fase en el patrón.",
        "keywords": ["corte", "transición", "fase", "patrón", "umbral"],
        "tree": "Transición (simplificado): cierre y relevo.",
        "notes": "Cambio de fase, sin predicción.",
    },
    "La Templanza": {
        "core": "Mezcla de corrientes: equilibrar para estabilizar forma nueva.",
        "keywords": ["mezcla", "corriente", "equilibrio", "estabilidad", "medida"],
        "tree": "Síntesis (simplificado): integrar flujos del Árbol.",
        "notes": "Síntesis como operación formal.",
    },
    "El Diablo": {
        "core": "Atadura de forma: fijación que densifica el canal.",
        "keywords": ["atadura", "fijación", "densidad", "canal", "imagen"],
        "tree": "Densidad (simplificado): forma fijada en el canal.",
        "notes": "Describe densidad, sin moralizar.",
    },
    "La Torre": {
        "core": "Ruptura de estructura: caída de forma rígida y descarga.",
        "keywords": ["ruptura", "descarga", "caída", "estructura", "liberación"],
        "tree": "Descarga (simplificado): colapso de forma fija.",
        "notes": "Evento de ruptura de forma, no advertencia.",
    },
    "La Estrella": {
        "core": "Orientación: señal clara que guía la recomposición del patrón.",
        "keywords": ["orientación", "señal", "recomposición", "claridad", "flujo"],
        "tree": "Orientación (simplificado): señal en el sendero.",
        "notes": "Se describe orientación, sin promesa.",
    },
    "La Luna": {
        "core": "Reflejo velado: tránsito por símbolos indirectos y umbrales.",
        "keywords": ["reflejo", "velado", "tránsito", "umbral", "marea"],
        "tree": "Umbral (simplificado): lo indirecto como canal.",
        "notes": "Lo velado como dinámica de símbolos, no diagnóstico.",
    },
    "El Sol": {
        "core": "Claridad de forma: visibilidad y coherencia del patrón.",
        "keywords": ["claridad", "visibilidad", "coherencia", "forma", "presencia"],
        "tree": "Claridad (simplificado): patrón visible.",
        "notes": "Describe claridad, no promesa.",
    },
    "El Juicio": {
        "core": "Llamado del patrón: reorden por señal mayor y cambio de nivel.",
        "keywords": ["llamado", "reorden", "señal", "umbral", "patrón"],
        "tree": "Reorden (simplificado): respuesta a señal mayor.",
        "notes": "Reorden estructural, sin sentencia.",
    },
    "El Mundo": {
        "core": "Integración total: cierre del ciclo y síntesis de forma completa.",
        "keywords": ["integración", "totalidad", "cierre", "síntesis", "ciclo"],
        "tree": "Malkut (simplificado): forma completa manifestada.",
        "notes": "Totalidad como estructura integrada.",
    },
}

