# Generated by Django 5.2.9 on 2026-01-25 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0084_add_bioemotional_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de la inquiry (ej: astro_current_life_events)', max_length=50, unique=True)),
                ('source_module', models.CharField(choices=[('astrology', 'Astrología'), ('cabala', 'Cábala'), ('transgenerational', 'Transgeneracional'), ('bioemotional', 'BioEmocional'), ('mshe', 'MSHE (Síntesis Holística)')], db_index=True, help_text='Módulo que solicita esta información', max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Crítica - Sin esto el módulo no funciona bien'), ('important', 'Importante - Mejora significativa'), ('optional', 'Opcional - Enriquecimiento')], db_index=True, default='important', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Categoría interna (ej: contexto_temporal, sintomas_somaticos)', max_length=50)),
                ('question_type', models.CharField(choices=[('scale_1_10', 'Escala 1-10'), ('yes_no', 'Sí/No'), ('text_short', 'Texto corto (max 300 chars)'), ('text_long', 'Texto largo (max 2000 chars)'), ('choice_single', 'Selección única'), ('choice_multi', 'Selección múltiple'), ('body_map', 'Mapa corporal interactivo')], max_length=20)),
                ('question_text', models.TextField(help_text='Texto completo de la pregunta')),
                ('question_text_short', models.CharField(blank=True, help_text='Versión corta para widgets y listas', max_length=100)),
                ('help_text', models.TextField(blank=True, help_text='Texto de ayuda para el paciente')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder para campos de texto', max_length=200)),
                ('choices', models.JSONField(blank=True, help_text='Lista de opciones para choice_single/choice_multi', null=True)),
                ('scale_labels', models.JSONField(blank=True, help_text="Labels para escalas (ej: {1: 'Muy bajo', 10: 'Muy alto'})", null=True)),
                ('validation', models.JSONField(blank=True, help_text='Reglas de validación (min_length, max_length, etc.)', null=True)),
                ('trigger_condition', models.JSONField(blank=True, help_text='Condiciones para activar esta inquiry', null=True)),
                ('valid_for_days', models.PositiveIntegerField(default=90, help_text='Días que una respuesta permanece válida')),
                ('follow_up', models.JSONField(blank=True, help_text='Lógica de preguntas de seguimiento', null=True)),
                ('dynamic', models.BooleanField(default=False, help_text='Si es dinámica, se aplica por cada entidad')),
                ('applies_per', models.CharField(blank=True, help_text='Modelo al que se aplica si es dinámica (ej: GenealogyPerson)', max_length=50)),
                ('sensitive', models.BooleanField(default=False, help_text='Marca si contiene información sensible')),
                ('opt_out_visible', models.BooleanField(default=True, help_text='Si el paciente puede ver y usar la opción de omitir')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Definición de Inquiry',
                'verbose_name_plural': 'Definiciones de Inquiries',
                'ordering': ['source_module', 'priority', 'code'],
                'indexes': [models.Index(fields=['source_module', 'priority'], name='inquiry_inq_source__537624_idx'), models.Index(fields=['is_active', 'source_module'], name='inquiry_inq_is_acti_733d05_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientInquiryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_entity_type', models.CharField(blank=True, help_text='Tipo de entidad relacionada (ej: GenealogyPerson)', max_length=50)),
                ('related_entity_id', models.PositiveIntegerField(blank=True, help_text='ID de la entidad relacionada', null=True)),
                ('response_value', models.JSONField(help_text='Valor de la respuesta (estructura depende del question_type)')),
                ('collected_by', models.CharField(choices=[('patient_self', 'Auto-completado por paciente'), ('therapist_session', 'Recolectado en sesión por terapeuta'), ('intake_form', 'Formulario de intake'), ('questionnaire', 'Cuestionario pre-sesión')], default='therapist_session', max_length=20)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración calculada', null=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Si la respuesta sigue siendo válida')),
                ('collected_by_user', models.ForeignKey(blank=True, help_text='Usuario que registró la respuesta (terapeuta si fue en sesión)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_inquiry_responses', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inquiry.inquirydefinition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_responses', to='api.patient')),
                ('session', models.ForeignKey(blank=True, help_text='Sesión en la que se recolectó (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_responses', to='api.session')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Nueva respuesta que reemplaza esta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='inquiry.patientinquiryresponse')),
            ],
            options={
                'verbose_name': 'Respuesta de Inquiry',
                'verbose_name_plural': 'Respuestas de Inquiries',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['patient', 'inquiry', '-collected_at'], name='inquiry_pat_patient_7acde8_idx'), models.Index(fields=['patient', 'is_valid'], name='inquiry_pat_patient_c0eb36_idx'), models.Index(fields=['inquiry', 'is_valid'], name='inquiry_pat_inquiry_bf7ce3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_valid', True), ('related_entity_id__isnull', True)), fields=('patient', 'inquiry'), name='unique_valid_response_per_patient_inquiry')],
            },
        ),
    ]
